### ISSUE TITLE
invoke-ai.github.io/InvokeAI is live 🎉, has some warts 😞

### ISSUE THREAD

**Issue by tildebyte** [invoke-ai/InvokeAI#1013]
**Describe the bug**
Various warts and nitpicks in the project documentation website

- references to lstein/stable-diffusion (instead of InvokeAI) and "dream script"
- unrendered emojis (":simple-nvidia:")
- 'Changelog' renders as "**Changelog**"
- discord badge linkURL are incorrect (check the repo README for the correct badge/URL)
- Probably other

**Comment by mauwii** [comment]
Hi, yes I can take a look ☺️

**Comment by tildebyte** [comment]
Note that some things have already been sorted

**Comment by mauwii** [comment]
I guess u mean #1026 🤔

**Comment by mauwii** [comment]
So I think I found the reason why again and again the emojis where broken: It is the GH-Action...

Two tings: it never happens when deployed manually (mkdocs gh-deploy), and after just updating the GH-Action to only use a python task, install requirements and push the docs, the Problem also not happens 🥳

**Comment by psychedelicious** [comment]
The issues here were resolved in #1032 .
