### ISSUE TITLE
ONNX Support for AMD GPU on Windows

### ISSUE THREAD

**Issue by 19wolf** [invoke-ai/InvokeAI#1019]
**Is your feature request related to a problem? Please describe.**
AMD GPU doesn't work on Windows

**Describe the solution you'd like**
It is possible to make it work using ONNX models

**Describe alternatives you've considered**
I have it working as a proof of concept using the instructions from these blog posts and related github repo: 
- https://www.travelneil.com/stable-diffusion-windows-amd.html
- https://www.travelneil.com/stable-diffusion-updates.html
- https://github.com/pingzing/stable-diffusion-playground

**Comment by LexiconCode** [comment]
This looks like it would be nice feature to have especially with the new AMD GPU's coming out on the 13th. In addition I haven't seen AMD hardware supported in any popular stable diffusion front end repository. 

Turns out the model needs to be converted a ONNX model fortunately huggingface maintains the script do just that.
https://github.com/huggingface/diffusers/blob/main/scripts/convert_stable_diffusion_checkpoint_to_onnx.py

**Comment by xzuyn** [comment]
any progress on this? we've been using onnx for a while with good results. I can personally get to 1088x1088 (or 876x1344) with my rx 480 8gb using max attention slicing.

https://github.com/azuritecoin/OnnxDiffusersUI/
https://github.com/Amblyopius/Stable-Diffusion-ONNX-FP16

**Comment by 19wolf** [comment]
Hi this is closed as "completed" but I don't see any linked merges or pulls or code or documentation about installing with an AMD GPU on Windows- in the installer there seems to be no option for AMD either.
