### ISSUE TITLE
Documentation for updating the app and adding dependency changes to release notes

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1037]
Congratz on the new 2.0 release. Lot's of good stuff to play with. 

Just wondering if there is any recommendation for upgrading to the latest? Also, does the dependencies have changed? If yes, it would be nice to have notes in the release description.

**Comment by NickBarreto** [comment]
I was able to upgrade on an M1 mac relatively simply, but it did involve rebuilding the whole conda environment.

Once you've pulled the most recent changes in the main branch, run:

```
conda env remove -n ldm
conda clean --yes --all
PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yml
```

After that everything ran as expected. In a sense it's a little easier than a full install because you know all the dependencies outside of Conda are already installed and available.

Rebuilding in different platforms is going to be a little different.

I agree some upgrade instructions are probably worth adding in to the documentation. I can probably to together a pull request but I don't have access to other platforms so I can't confirm the best way to go about it in Windows or Linux.

**Comment by Neosettler** [comment]
Here's an idea. Maybe a portable "package" available for each release/platform? No more Python upkeep, for humanity sake!

**Comment by psychedelicious** [comment]
Settings this as a documentation request for:
- Instructions for updating in the docs
- Also maybe dependency changes in release notes

@lstein since I think you are managing releases mostly now

**Comment by Neosettler** [comment]
@lstein please consider adding this to next releases. Thank you you.
