### ISSUE TITLE
Black images on Mac when using ddim/plms

### ISSUE THREAD

**Issue by skurovec** [invoke-ai/InvokeAI#1051]
**Describe your environment**
-    GPU: m1 max
-    RAM: 32GB
 -   CPU arch: arm
 -   OS: macOS
 -   Python: Miniconda, as per installation instructions number 2
 -   Branch: main
 -   Commit: 10d8d1bb25aa51f8eae975e4c9d937bb1bb1ff6f

**Describe the bug**
Black images after generating images

**To Reproduce**
1. ```"banana sushi" -s 50 -W 512 -H 768 -C 8 -A ddim -n 30``` to dream prompt

**Expected behavior**
30 banana sushi images, without black ones

**Actual behavior**
25 banana sushi images, 5 black ones

**Additional context**
Maybe related to https://github.com/invoke-ai/InvokeAI/issues/1045

Tried with 512x512, same issue.

**Comment by Any-Winter-4079** [comment]
I can reproduce your issue (but not https://github.com/invoke-ai/InvokeAI/issues/1045 so far)
<img width="300" alt="image" src="https://user-images.githubusercontent.com/50542132/195080697-f6cc2030-829d-4c37-be9f-c8e80e9ff297.png">

**Comment by Any-Winter-4079** [comment]
@skurovec have you experienced the same in other samplers?

**Comment by skurovec** [comment]
no, but I will do some tests just to be sure

**Comment by lstein** [comment]
I think this is related to a bug reported (and I thought fixed) about a month ago. There was a bug in the `ddim` and `plms` samplers that caused black images when certain values of the denoising timestep array were hit. I think one of the cursed values was 1000, but I'll have to go back and refresh my memory on this. We had a workaround, but perhaps it fails on Macs.

I'll try to reproduce on Linux, but it would be useful to know whether the black images appear when using the `plms` and `k_euler` samplers. My bet is that `plms` will be problematic and `k_euler` fine.

**Comment by Any-Winter-4079** [comment]
`plms` yes

**Comment by lstein** [comment]
Just ran 30 each of `ddim` and `plms` on Linux CUDA system and was unable to reproduce black images. It may be an M1-specific problem.

When you have a chance, could you bisect to see if a recent commit is to blame? I think we would have had reports of this if the bug were old and 1 in 5 images were coming up black. Another data point would be to determine if the black images are reproducible on an individual basis by providing the seed of the bad image. This will help debugging considerably!

**Comment by Any-Winter-4079** [comment]
Providing the seed is not enough to reproduce the black image.
`000009.728100201.png`
<img width="100" alt="Screenshot 2022-10-11 at 15 09 02" src="https://user-images.githubusercontent.com/50542132/195099512-6c43e3e6-dd6b-48c7-bc4e-bcdb55718cb0.png">
`"banana sushi" -s 50 -S 728100201 -W 512 -H 768 -C 8.0 -A plms`
`000013.728100201.png`
<img width="100" alt="Screenshot 2022-10-11 at 15 17 26" src="https://user-images.githubusercontent.com/50542132/195101395-27046ab5-bebd-40df-82eb-afd56622044d.png">


Yes, (around) 1 in 5 sounds very reasonable but not exactly one every five for `plms` nor `ddim` sampling
`"banana sushi" -s 50 -W 512 -H 768 -C 8 -A plms -n 5` 0 of 5 are black (but sometimes occurs)
<img width="187" alt="Screenshot 2022-10-11 at 15 11 55" src="https://user-images.githubusercontent.com/50542132/195100131-925e5079-e0fa-4f4e-a175-d2ad8e77b946.png">
`"banana sushi" -s 50 -W 512 -H 768 -C 8 -A ddim -n 5` 2 of 5 are black
<img width="187" alt="Screenshot 2022-10-11 at 15 16 19" src="https://user-images.githubusercontent.com/50542132/195101151-b0da6b38-c2d1-4c1e-8f04-c2cd9407e303.png">

**Comment by Any-Winter-4079** [comment]
@skurovec try this commit
`git checkout 461e6626`
It seems to work well?

If so we can bisect, but I share it with you because I'm running out of battery here at uni :)

**Comment by skurovec** [comment]
testing, so far 5 and 5 ok
testing bigger batch, it will take some time

**Comment by skurovec** [comment]
29/50, so far ok (ddim)

**Comment by Any-Winter-4079** [comment]
3bc1ff5 might also be okay.

**Comment by skurovec** [comment]
https://github.com/invoke-ai/InvokeAI/commit/3bc1ff5e5a23d19aade515870d90dc09b322d79f 50/50 ok

**Comment by skurovec** [comment]
https://github.com/invoke-ai/InvokeAI/commit/280e2899d73e13b78af819822073c6f4d03f1106 fourth image black

**Comment by Any-Winter-4079** [comment]
Okay, then
```
git bisect bad 280e289
git bisect good 3bc1ff5
```
Next test: `git checkout ce8c238`

**Comment by lstein** [comment]
I hope you folks have already realized this, but you can run the bisect
with a small number of steps.

Unless, of course, the black images appear over the course of a series of
steps, which would in itself be a revealing data point.

Lincoln

**Comment by Any-Winter-4079** [comment]
I think I made a mistake checking out some other branch in between these bisects or something :) Bad thing split attention between this and class.
I'll get back to this in about 45 minutes, and I will revise all of the tests done.
In any case, we are pretty close to the commit.

**Comment by skurovec** [comment]
culprit 8faa06fb152fca2b11a72fdee6656e56ee46d631

**Comment by Any-Winter-4079** [comment]
Ahh, so it was between these commits after all.
`--ancestry-path ce8c238..280e289`
```
280e2899d73e13b78af819822073c6f4d03f1106
82b0bb838c9495d6505ea8902c5db99777c939ca
8482518618186ecc4919d2abd16dfd7f0eb6ee66
6425bda6630128e92ac017391bd3b853834dd92b
12413b0be69b51bedb6040b06d91a4d73f80bf7e
789714b0b1364365c67e41e02b5548d9897f0260
bb7629d2b8f15647dbe3706c5d0b848b07c6012f
c5344acb2542cdf1d6fc64e4e00f4cd7467dc186
6e2fd2affe023d486942f8ca9d377b6fd4e3ef09
8faa06fb152fca2b11a72fdee6656e56ee46d631 <-

```

**Comment by Any-Winter-4079** [comment]
> culprit [8faa06f](https://github.com/invoke-ai/InvokeAI/commit/8faa06fb152fca2b11a72fdee6656e56ee46d631)

This one generates black images.

**Comment by Any-Winter-4079** [comment]
So that commit basically reverted the effects of https://github.com/invoke-ai/InvokeAI/pull/579/
which also provided `k_euler_a` and `k_dpm_2_a` reproducibility (getting the same image using the same seed).
Without that change, that was also gone, even though no one reported it yet:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/50542132/195176965-91ce02f9-f51f-4b2e-8840-208297af4c3a.png">



I think moving forward, it'd be good to either document the code (e.g. this has x purpose for 4GB VRAM, this has y purpose for mps, so it doesn't get inadvertently removed) or run some tests at least on cuda and mps (both) before passing any change that modifies the samplers behavior.

I think this idea of generating a thorough set of tests is less time consuming than debugging errors all the time, especially errors that have already been solved.

Does this commit change reproducibility? Run a test where you generate an image and compare it with an old one. Do they match?
Does this commit generate black images? Run a test creating a bunch of images and check if pixels are all (or mostly all) black (0) in any of images generated.
Does this commit affect variations (-v)? Run a test with different strength values and maybe create a histogram to see changes. Are the results close to the old behavior?

Otherwise, there's so many things to consider that a quick manual test (and mostly, on one's computer) is unlikely to catch every problem that might be getting indadvertedly introduced.

**Comment by Any-Winter-4079** [comment]
Oh and nice find @skurovec ! Feel free to open a PR!
