### ISSUE TITLE
2.0 --grid no working?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1065]
Greetings,

Could someone confirmed that --grid or -g does save a grid? Not having any effect on Windows so far.

**Comment by lstein** [comment]
Since the WebGUI doesn't have a grid option, can I assume you are using the command-line interface?

I can confirm that `--grid` or `-g`  works for me at the `invoke>` command line if you invoke it like this:

~~~
invoke> an old man and the sea -n6 -g
~~~

If you provide `-g` at the time you launch the script, grids should now become the default:

~~~
python3 scripts\invoke.py --grid
~~~

If it is not behaving this way, please respond with more information about your platform and install method.

**Comment by Neosettler** [comment]
thank you [lstein](https://github.com/lstein), Not sure why grid cant be used with all images at the same time so I made modification to 1.x before to handle images and grid to be saved by removing else after do_grid or whatnot. That same modification no longer works though, I'm still digging to find why.

**Comment by Neosettler** [comment]
the whole logic with grid/individual is funky, not sure that is necessary. Please, consider allowing both grid and images to be saved.

**Comment by Neosettler** [comment]
Oh I got it, the grid is overtighten by an image as they have the save name.

**Comment by lstein** [comment]
Yeah, in fact grid generation should be treated like a post-processing step akin to upscaling and face reconstruction. It's weird now because of the way it was integrated into image generation in the original CompViz code.

We've got a new service-oriented architecture coming along in which each image manipulation step is its own callable node: PR #1047 . I'm hoping that we can turn grid-generation into a discrete post-processing step.
