### ISSUE TITLE
Version 2.0 on Intel processor results in conda conflicts

### ISSUE THREAD

**Issue by jkostolansky** [invoke-ai/InvokeAI#1067]
I'm trying to install the new 2.0 version (`main` branch) on my MacBook Pro with Intel Core i9 processor. But this command:

```bash
PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-64 conda env create -f environment-mac.yml
```

Always ends with:

```
Found conflicts! Looking for incompatible packages.
```

When I try it with the `release-1.14.1` version, it works correctly. Is it a bug or am I doing something wrong?

**Comment by rpfile** [comment]
seems like the conda environment always causes issues like this, since there are so many deps and many of them are moving targets.

i resolved this by installing mamba, which provides more coherent conflict resolution information. at some point along the line the conflicts were resolved by installing protobuf 3.20.x, however, it appears that textual inversion breaks with protobuf > 3.19.4, so that's not a proper solution.

with my most recent conflict, opencv-python was the problem. the environment calls for 4.6.0 and 4.6.0.66 was available but for some reason did not satisfy the dependency. so i explicitly called out 4.6.0.66 and that worked.

YMMV; i am running on an M1 mac.

**Comment by i3oc9i** [comment]
try this sequence to start a clean environment

```
conda deactivate

conda env remove -n invokeai

conda clean --yes --all

PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-64 conda env create -f environment-mac.yml
```

**Comment by marktermaat** [comment]
I have the same issue. Removing and cleaning the environment didn't work for me. For now I'm back to 1.14.

**Comment by michaelezra** [comment]
I had to do cleaning twice (M1 Max MacOS) and then the last time I recall, created condo environment with this command:
conda env create -f environment-mac.yml

**Comment by lstein** [comment]
FYI we're working on a streamlined "1-click" install script for all major platforms. Hopefully will be ready soon.

**Comment by jroxendal** [comment]
this recently started acting up for me too, tried to install mamba using conda but getting the same conflict issues there too :-/ oh, python dependency management.

**Comment by jkostolansky** [comment]
It's working for me now after the latest changes. Thanks!
