### ISSUE TITLE
Image to Image improperly adjusting target resolution

### ISSUE THREAD

**Issue by PutUsernameHere** [invoke-ai/InvokeAI#1098]
**Describe your environment**
- GPU: cuda
- VRAM: 11GB
- CPU arch: x86
- OS: Windows
- Python: Anaconda
- Branch: Development
- Commit: ce5e57d8285aa21221c707ad5a2e92c4040a0d6a

**Describe the bug**
When using the img2img's WebUI the init image resolution is 1280x720 , with the output resolution being set to 1280x768. Instead of outputting a height of 768, it outputs a height of 704. This also happens when the init image has a height of 704.
Here's the relevant logging:
```
>> image will be resized to fit inside a box 1280x768 in size.
>> after adjusting image dimensions to be multiples of 64, init image is 1280x704
```
This seems strange, since 768 is already a multiple of 64.

**To Reproduce**
1. In Img2Img in the WebUI, set an init image with a resolution of 1280x720
2. Set the target resolution to 1280x768, with `Fit Initial Image To Output Size` enabled
3. See the final image being 1280x704

**Expected behavior**
A 1280x768 output image

**Comment by psychedelicious** [comment]
This is the expected behavior, the result image will be contained to the target resolution, using the aspect ratio closest to the original image, rounding to the nearest multiple of 64.

So, when fit to 1280x768px:
- Initial image @ 1280x735px fits to 1280x704px
- Initial image @ 1280x736px fits to 1280x768px
