### ISSUE TITLE
GitHub has detected several security issues in InvokeAI dependencies

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#1149]
Hi developers,

GitHub's dependabot service just warned me about three vulnerabilities in InvokeAI due to security holes in pytorch-lightning and protobufs:

https://github.com/invoke-ai/InvokeAI/security/dependabot

They recommend the following version upgrades:
```
pytorch-lightning>=1.6.0
protobuf>=3.19.5
```

Before I go ahead and make these changes, are there any incompatibility issues I should be aware of when using these later versions? I'm particularly concerned about Macs, which seem to be very finicky about the library versions.

**Comment by skurovec** [comment]
environment-mac already using
```
pytorch-lightning==1.7.5
protobuf==3.19.5
```

not sure about ```requirements-mac-MPS-CPU.txt``` where is ```protobuf==3.19.4```, but I am not using it myself

**Comment by Vargol** [comment]
There was an issue with pip protobuf missing a stmbol/function at 1.9.5 and up, it would need testing again to find a compatible combination

**Comment by Vargol** [comment]
okay, I've had a play.

The old bug was an issue between transformers and protobuf. This seems to be fixed in later versions of transformers and I can seeming use any protobuf < 4.0.0 if I do an uninstall/install . 

From an up install via  `pip install -r equirements-mac-MPS-CPU.txt `using a purged cache and fresh clone 
where I've changed it to `protobuf<4.0.0  `something else brings in down to 3.19.6, I get this at the end

```
Installing collected packages: protobuf, invoke-ai
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
  Running setup.py develop for invoke-ai
Successfully installed invoke-ai-2.0.0 protobuf-3.19.6

```
I can preload the models, which is where the original conflict showed up and I ran a couple of prompts
successfully.

final versions of note...

```
pytorch-lightning           1.7.7
protobuf                    3.19.6
transformers                4.21.3
```

**Comment by lstein** [comment]
Great. I'm going to go ahead and update the requirements to the versions
that GitHub recommends. I'll do it in both `main` and `development`.

Lincoln

**Comment by lstein** [comment]
2.0.2 point release coming out now
