### ISSUE TITLE
Error w/ 'conda env create -f environment-mac.yml' on M1 Mac

### ISSUE THREAD

**Issue by movinimage** [invoke-ai/InvokeAI#1158]
When I run this command:

PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yml

It compiles successfully for a while...and then I get many instances of the following error:

error[E0433]: failed to resolve: use of undeclared crate or module `ctor`
        --> src/decoders.rs:59:1
         |
      59 | #[pymethods]
         | ^^^^^^^^^^^^ use of undeclared crate or module `ctor`
         |
         = note: this error originates in the attribute macro `pyo3::inventory::ctor` which comes from the expansion of the attribute macro `pymethods` (in Nightly builds, run with -Z macro-backtrace for more info)

I believe this was the specific sub-command running at this time:

 Running `rustc --crate-name tokenizers --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no --crate-type cdylib -C 'link-args=-undefined dynamic_lookup -Wl,-install_name,@rpath/tokenizers.cpython-39-darwin.so' --cfg 'feature="default"' -C ...

**Comment by psychedelicious** [comment]
I have the same issue, the final error was:
```
  ERROR: Failed building wheel for tokenizers
ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects

failed

CondaEnvException: Pip failed
```

I fixed it by running:
```
pip install tokenizers
pip install transformers
```

And then removing the version requirement from `environment-mac.yml`:
```
      - transformers
```

I think if I only did the last step, it might work? Unsure, don't have time to test right now.

**Comment by movinimage** [comment]
I tried what you suggest, but I end up having to manually 'pip install' lots of modules. Finally I end up missing 'Taming' and when I try to manually install that one I get:

ERROR: Could not find a version that satisfies the requirement taming (from versions: none)
ERROR: No matching distribution found for taming

**Comment by movinimage** [comment]
Ok. I have it working.

I ran:
`pip install tokenizers
pip install transformers`

Then removed the version requirement from environment-mac.yml:
` - transformers`

Then, I re-ran (with --force at the end):
`PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yml --force`

**Comment by whosawhatsis** [comment]
Thank you! I've been tearing my hair out trying to get this to work all day.

**Comment by psychedelicious** [comment]
I didn't fully describe the process I went through; it was:
- Create the conda env, wait for it to fail
- Activate the environment
- run:
```
pip install tokenizers
pip install transformers
```
- Remove the version requirement
- Update the conda env `PIP_EXISTS_ACTION=w mamba env update -f environment-mac.yml` (I use mamba instead of conda but it's does the same thing)

**Comment by GarthSnyder** [comment]
To expand upon @movinimage's solution, it worked for me to simply adjust the 

```
- transformers
```

line in environment-mac.yml (removing the version number) and then delete and re-create the InvokeAI environment from scratch using the standard command from the installation guide. The packages are cached, so it goes a lot faster the second time.

**Comment by whosawhatsis** [comment]
That seemed to be all that was necessary for me, as well.

**Comment by movinimage** [comment]
Do we know why removing the transformers version is required? And, is it affecting the operation of SD in some unseen way?

**Comment by damian0815** [comment]
interesting, i ran this yesterday on my M1 and it built the conda env just fine with no changes necessary

**Comment by jameslanman** [comment]
Sadly, it is still not working for me. After fresh installs of Python, Homebrew (even using the Intel version of Homebrew in a separate file path to install rust) and utilizing 'pip cache purge' I keep getting the following error at the `(invokeai) python scripts/preload_models.py` step:
 
`RuntimeError: Failed to import transformers.models.clip because of the following error (look up to see its traceback):
dlopen(/Users/username/miniconda3/envs/invokeai/lib/python3.9/site-packages/tokenizers/tokenizers.cpython-39-darwin.so, 0x0002): tried: '/Users/username/miniconda3/envs/invokeai/lib/python3.9/site-packages/tokenizers/tokenizers.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))`

Pulling my hair out the past couple of days here. I tried @movinimage 's suggestion but alas, no dice still. Any ideas?

**Comment by psychedelicious** [comment]
I had a quick search and found some similar issues with a potential fix here https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2313

**Comment by jameslanman** [comment]
Update: I hope this helps someone get it working as well because that was incredibly frustrating. Running `pip install tokenizers==0.12.0` seemed to do the trick after trying many different things. Thank you @psychedelicious for pointing out that the [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2313 ) install suffered from a similar issue.

**Comment by TruongQuocTruong** [comment]
> Ok. I have it working.
> 
> I ran: `pip install tokenizers pip install transformers`
> 
> Then removed the version requirement from environment-mac.yml: ` - transformers`
> 
> Then, I re-ran (with --force at the end): `PIP_EXISTS_ACTION=w CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac.yml --force`

Thanks! I have done

**Comment by psychedelicious** [comment]
We should have this particular dependecy issue sorted across the repo now.
