### ISSUE TITLE
Slow generation on a fresh M1 install

### ISSUE THREAD

**Issue by jpiabrantes** [invoke-ai/InvokeAI#1252]
**Describe your environment**
- GPU: mps
- RAM: 16 Gb
- CPU arch: arm
- OS: macOS
- Python: 3.9.13, miniconda 4.12.0
- Branch: development (saw an [issue](https://github.com/invoke-ai/InvokeAI/issues/578) where the main branch was slower)
- Commit: 4104ac62709ab3ea2b5b2b876799a2b77592485f

**Description**
Running `python scripts/invoke.py` is taking ~120 seconds to generate an image (50 steps). I have read multiple people with the same computer as me MacBook Pro M1 16Gb achieving 30 seconds per image (4x faster)!

This is a fresh installation, how can I debug it?

Thank you very much for this awesome repo all your work 🙌

**Comment by michaelezra** [comment]
My test on  M1 Max 64Gb 32 GPU; SD1.5

>> Image generation requested: {'prompt': 'pretty landscape', 'iterations': 1, 'steps': 50, 'cfg_scale': 19, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_euler', 'seed': 1486323210, 'seamless': False, 'hires_fix': False, 'progress_images': False, 'variation_amount': 0}
ESRGAN parameters: False
GFPGAN parameters: False
>> Setting Sampler to k_euler
/Users/michaelezra/ai/stable-diffusion/ldm/modules/embedding_manager.py:155: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1659484611838/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  placeholder_idx = torch.where(
Generating:   0%|                                                                                                                                                                                                              | 0/1 [00:00<?, ?it/s]>> Sampling with k_euler starting at step 0 of 50 (50 new sampling steps)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:27<00:00,  1.80it/s]
>> Image generated: "/Users/michaelezra/ai/stable-diffusion/outputs/img-samples/003529.1486323210.png"███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:27<00:00,  1.89it/s]
Generating: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:28<00:00, 28.36s/it]
>> Usage stats:
>>   1 image(s) generated in 28.60s

**Comment by michaelezra** [comment]
The same with High Res = ON becomes 47 seconds:

>> Image generation requested: {'prompt': 'pretty landscape', 'iterations': 1, 'steps': 50, 'cfg_scale': 19, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_euler', 'seed': 1486323210, 'seamless': False, 'hires_fix': True, 'progress_images': False, 'variation_amount': 0}
ESRGAN parameters: False
GFPGAN parameters: False
Generating:   0%|                                                                                                                                                                                                              | 0/1 [00:00<?, ?it/s]>> Sampling with k_euler starting at step 0 of 50 (50 new sampling steps)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:26<00:00,  1.85it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:26<00:00,  1.91it/s]
>> Interpolating from 512x512 to 512x512 using DDIM sampling
>> Running DDIMSampler sampling starting at step 13 of 50 (37 new sampling steps)
Decoding image: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 37/37 [00:19<00:00,  1.86it/s]
>> Image generated: "/Users/michaelezra/ai/stable-diffusion/outputs/img-samples/003530.1486323210.png"███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 37/37 [00:19<00:00,  1.87it/s]
Generating: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:47<00:00, 47.35s/it]
>> Usage stats:
>>   1 image(s) generated in 47.51s

**Comment by michaelezra** [comment]
Leaving High Res on, changing size to 768x768 - 90 seconds

>> Image generation requested: {'prompt': 'pretty landscape', 'iterations': 1, 'steps': 50, 'cfg_scale': 19, 'threshold': 0, 'perlin': 0, 'height': 768, 'width': 768, 'sampler_name': 'k_euler', 'seed': 1486323210, 'seamless': False, 'hires_fix': True, 'progress_images': False, 'variation_amount': 0}
ESRGAN parameters: False
GFPGAN parameters: False
Generating:   0%|                                                                                                                                                                                                              | 0/1 [00:00<?, ?it/s]>> Sampling with k_euler starting at step 0 of 50 (50 new sampling steps)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:27<00:00,  1.84it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:27<00:00,  1.82it/s]
>> Interpolating from 512x512 to 768x768 using DDIM sampling
>> Running DDIMSampler sampling starting at step 13 of 50 (37 new sampling steps)

Decoding image:  22%|█████████████████████████████████████████▋                                                                                                                                                       | 8/37 [00:14<00:48,  1DecodingDecoding image: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 37/37 [01:02<00:00,  1.68s/it]
>> Image generated: "/Users/michaelezra/ai/stable-diffusion/outputs/img-samples/003531.1486323210.png"███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 37/37 [01:02<00:00,  1.66s/it]
Generating: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [01:30<00:00, 90.22s/it]
>> Usage stats:
>>   1 image(s) generated in 90.38s

**Comment by FreeBlues** [comment]
It looks like you are using CPU, check the info when invokeai start up

this is using GPU:

```
>> Using device_type mps
```

and this is usingCPU:

```
>> Using device_type cpu
```

**Comment by FreeBlues** [comment]
Another possibility is that you have a bit less memory. The M1 GPU seems to use main memory to simulate video memory. macOS requires at least 8gb of memory, so only 8GB is reserved for graphics cards

Also look at what kind of sampler you have chosen. On my computer, DDIM is the fastest, the others are slower. My ddim is 4~5s/it, the others are 8~9s/it

**Comment by michaelezra** [comment]
fyi this is my output on m1:
% python scripts/invoke.py --web --model stable-diffusion-1.5
* Initializing, be patient...
NOTE: Redirects are currently not supported in Windows or MacOs.
>> GFPGAN Initialized
>> CodeFormer Initialized
>> ESRGAN Initialized
>> Using device_type mps
>> Loading stable-diffusion-1.5 from models/ldm/stable-diffusion-v1/v1-5-pruned-emaonly.ckpt
   | LatentDiffusion: Running in eps-prediction mode
   | DiffusionWrapper has 859.52 M params.
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
   | Using more accurate float32 precision
>> Model loaded in 5.66s
>> Setting Sampler to k_lms

* --web was specified, starting web server...
>> Started Invoke AI Web Server!
>> Default host address now 127.0.0.1 (localhost). Use --host 0.0.0.0 to bind any address.
>> Point your browser at http://127.0.0.1:9090

**Comment by psychedelicious** [comment]
My M1 Pro 32GB unified memory (with, IIRC, 16 core GPU) takes 60 to 70 seconds to do 50 steps at 512x512 on k_lms. The unified memory spec seems to be the most impactful thing as far as generation times are concerned, for M1 devices. 

I don't think your results are too far out. It's possible other users were using lower step counts to get those numbers. 

As an aside, step count doesn't necessarily need to be up at 50 for good results. Have a play with different samplers and steps, even down to single digit steps can be good with some samplers.

**Comment by FreeBlues** [comment]
> My M1 Pro 32GB unified memory (with, IIRC, 16 core GPU) takes 60 to 70 seconds to do 50 steps at 512x512 on k_lms. The unified memory spec seems to be the most impactful thing as far as generation times are concerned, for M1 devices.
> 
> I don't think your results are too far out. It's possible other users were using lower step counts to get those numbers.
> 
> As an aside, step count doesn't necessarily need to be up at 50 for good results. Have a play with different samplers and steps, even down to single digit steps can be good with some samplers.

Indeed, fewer iterations can produce usable images.

My macbook pro 2020 is Intel CPU, with an outside GPU(RX 6600XT 8G VRam). However, it seems that all macOS uses the mps-based code handling process. I usualy use the ddim and 20 steps, and the resulting image looks pretty good.

@jpiabrantes I think you can do this by choosing fewer iterations first, you can quickly see the effect of generating the image, and if you feel the need to increase the number of iterations, then use more iterations, the advantage is that it saves time

**Comment by psychedelicious** [comment]
> My macbook pro 2020 is Intel CPU, with an outside GPU(RX 6600XT 8G VRam). However, it seems that all macOS uses the mps-based code handling process. I usualy use the ddim and 20 steps, and the resulting image looks pretty good.

Unfortunately macOS is stuck on MPS. There is no support for AMD graphics on macOS at all, so your GPU goes unused :(

**Comment by FreeBlues** [comment]
> > My macbook pro 2020 is Intel CPU, with an outside GPU(RX 6600XT 8G VRam). However, it seems that all macOS uses the mps-based code handling process. I usualy use the ddim and 20 steps, and the resulting image looks pretty good.
> 
> Unfortunately macOS is stuck on MPS. There is no support for AMD graphics on macOS at all, so your GPU goes unused :(

Read Apple's official website statement, using the M1/M2 series of the new model does not support external AMD graphics card, my old model is still usable, it is much faster than simply using the CPU. I feel like I'm still not living up to the full potential of eGPU, so I recently started learning PyTorch

**Comment by discordinated** [comment]
Mac Studio - M1 Max 32GB 10 Core CPU / 24 core GPU

Here's my test run for you. I could probably get it a little faster if I shut down everything else running on my machine. 

`>> Image generation requested: {'prompt': 'dream', 'iterations': 1, 'steps': 50, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 3472290490, 'seamless': False, 'hires_fix': False, 'progress_images': False, 'variation_amount': 0}
ESRGAN parameters: False
Facetool parameters: False
>> Setting Sampler to k_lms
>> Parsed prompt to FlattenedPrompt:[Fragment:'dream'@1.0]
Generating:   0%|                                         | 0/1 [00:00<?, ?it/s]>> Sampling with k_lms starting at step 0 of 50 (50 new sampling steps)
100%|███████████████████████████████████████████| 50/50 [00:28<00:00,  1.73it/s]
>> Image generated: "/Users/USERNAME/InvokeAI/outputs/img-samples/002779.3472290490.png"
Generating: 100%|█████████████████████████████████| 1/1 [00:32<00:00, 32.26s/it]
>> Usage stats:
>>   1 image(s) generated in 32.66s`

And then using high res fix I can get to 768x1024 comfortably:

`>> Image generation requested: {'prompt': 'dream', 'iterations': 1, 'steps': 50, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 1024, 'width': 768, 'sampler_name': 'k_lms', 'seed': 2152659154, 'seamless': False, 'hires_fix': True, 'progress_images': False, 'variation_amount': 0}
ESRGAN parameters: False
Facetool parameters: False
>> Parsed prompt to FlattenedPrompt:[Fragment:'dream'@1.0]
Generating:   0%|                                         | 0/1 [00:00<?, ?it/s]>> Sampling with k_lms starting at step 0 of 50 (50 new sampling steps)
100%|███████████████████████████████████████████| 50/50 [00:34<00:00,  1.46it/s]
100%|███████████████████████████████████████████| 50/50 [00:34<00:00,  1.46it/s]
>> Interpolating from 448x640 to 768x1024 using DDIM sampling
>> Running DDIMSampler sampling starting at step 13 of 50 (37 new sampling steps)
Decoding image: 100%|███████████████████████████| 37/37 [01:55<00:00,  3.12s/it]
>> Image generated: "/Users/si/InvokeAI/outputs/img-samples/002779.2152659154.png"
Generating: 100%|████████████████████████████████| 1/1 [02:39<00:00, 159.95s/it]
>> Usage stats:
>>   1 image(s) generated in 160.13s
`

On my wife's M1 Max 64 GB - 10 core cpu 32 core gpu :

`>> Image generation requested: {'prompt': 'dream', 'iterations': 1, 'steps': 50, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 512, 'width': 512, 'sampler_name': 'k_lms', 'seed': 3247261397, 'seamless': False, 'hires_fix': False, 'progress_images': False, 'variation_amount': 0}
ESRGAN parameters: False
Facetool parameters: False
>> Setting Sampler to k_lms
>> Parsed prompt to FlattenedPrompt:[Fragment:'dream'@1.0]
Generating:   0%|                                         | 0/1 [00:00<?, ?it/s]>> Sampling with k_lms starting at step 0 of 50 (50 new sampling steps)
100%|███████████████████████████████████████████| 50/50 [00:27<00:00,  1.81it/s]
>> Image generated: "/Users/Ellie/InvokeAI/outputs/img-samples/001426.3247261397.png"
Generating: 100%|█████████████████████████████████| 1/1 [00:28<00:00, 28.28s/it]
>> Usage stats:
>>   1 image(s) generated in 28.49s`

and for the same res with high res fix:

`>> Image generation requested: {'prompt': 'dream', 'iterations': 1, 'steps': 50, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 1024, 'width': 768, 'sampler_name': 'k_lms', 'seed': 25756624, 'seamless': False, 'hires_fix': True, 'progress_images': False, 'variation_amount': 0}
ESRGAN parameters: False
Facetool parameters: False
>> Parsed prompt to FlattenedPrompt:[Fragment:'dream'@1.0]
Generating:   0%|                                         | 0/1 [00:00<?, ?it/s]>> Sampling with k_lms starting at step 0 of 50 (50 new sampling steps)
100%|███████████████████████████████████████████| 50/50 [00:33<00:00,  1.49it/s]
100%|███████████████████████████████████████████| 50/50 [00:33<00:00,  1.47it/s]
>> Interpolating from 448x640 to 768x1024 using DDIM sampling
>> Running DDIMSampler sampling starting at step 13 of 50 (37 new sampling steps)
Decoding image: 100%|███████████████████████████| 37/37 [01:48<00:00,  2.92s/it]
>> Image generated: "/Users/Ellie/InvokeAI/outputs/img-samples/001427.25756624.png"
Generating: 100%|████████████████████████████████| 1/1 [02:23<00:00, 143.45s/it]
>> Usage stats:
>>   1 image(s) generated in 143.69s`

So the extra GPU cores makes it faster... but not massively at this res.

However if I try and go even 1 step above 768 x 1024 I get 50+ secs/it - where her machine can handle a bit more res due to the extra memory. I've not tested the upper limit on her machine yet. I do wish I'd got an Ultra with 128GB RAM now however. :)

**Comment by psychedelicious** [comment]
> Read Apple's official website statement, using the M1/M2 series of the new model does not support external AMD graphics card, my old model is still usable, it is much faster than simply using the CPU. I feel like I'm still not living up to the full potential of eGPU, so I recently started learning PyTorch

PyTorch does not support AMD GPUs on macOS, at all - and so SD by extension also does not :(

**Comment by psychedelicious** [comment]
> I do wish I'd got an Ultra with 128GB RAM now however. :)

You're telling me, buddy! 

However what I really want now that SD exists is a gaming/workstation with a 4090... 50 steps in a few seconds...

**Comment by discordinated** [comment]
> However what I really want now that SD exists is a gaming/workstation with a 4090... 50 steps in a few seconds...

Indeed but I can't justify that type of machine solely for running SD on. 

I could self justify a high end Mac for many other productive reasons. It'll be interesting to see what the Mac Pro brings. [If the rumours are true](https://www.macrumors.com/2022/08/17/apple-silicon-mac-pro-configurations/)

**Comment by FreeBlues** [comment]
> > Read Apple's official website statement, using the M1/M2 series of the new model does not support external AMD graphics card, my old model is still usable, it is much faster than simply using the CPU. I feel like I'm still not living up to the full potential of eGPU, so I recently started learning PyTorch
> 
> PyTorch does not support AMD GPUs on macOS, at all - and so SD by extension also does not :(

I'm not really sure, because I'm new to all of this stuff, and I see a lot of different things, but I do see eGPU being used when I'm generating images

<img width="1044" alt="截屏2022-10-25 22 11 18" src="https://user-images.githubusercontent.com/3386551/198508387-4b82e1d1-12f8-474a-ab94-567a79ee8def.png">

<img width="925" alt="截屏2022-10-25 22 09 08" src="https://user-images.githubusercontent.com/3386551/198508502-8bc69b84-c2b7-4ed4-a3be-ec1d7711ce9d.png">

I think the most likely scenario is that macOS encapsulates all GPU resources, including the M1/M2 family, and the eGPU in a unified way, called mps, with the same external interface, so the eGPU is likely to be invoked in the form of mps.

**Comment by psychedelicious** [comment]
> I think the most likely scenario is that macOS encapsulates all GPU resources, including the M1/M2 family, and the eGPU in a unified way, called mps, with the same external interface, so the eGPU is likely to be invoked in the form of mps.

Wow, that is really cool! I had no idea this was possible. Thanks for sharing this.

**Comment by FreeBlues** [comment]
@psychedelicious You are welcome. And thanks for your work to make invokeai support macos, btw. invokeai is the best performance repo I've used so far, on macOS.

**Comment by taconugget** [comment]
> > My macbook pro 2020 is Intel CPU, with an outside GPU(RX 6600XT 8G VRam). However, it seems that all macOS uses the mps-based code handling process. I usualy use the ddim and 20 steps, and the resulting image looks pretty good.
> 
> Unfortunately macOS is stuck on MPS. There is no support for AMD graphics on macOS at all, so your GPU goes unused :(

This isn't totally true. I have an Intel Mac with a Radeon 6900XT. Im running the latest pytorch 1.13.0 and I am using the GPU just fine. Its not as fast as when I boot into linux and use ROCm drivers but it does work. To get a 512x512 50step image it takes roughly 30sec in MacOSX, same machine booted in linux will take about 7sec per frame.

at startup I see: 
>> Using device_type mps

generating I see:
>> Sampling with k_euler_ancestral starting at step 0 of 50 (50 new sampling steps)
100%| | 50/50 [00:32<00:00,  1.52it/s]
>> Image generated: "/Users/brad/InvokeAI/outputs/img-samples/001012.3885546993.png|| 50/50 [00:32<00:00,  1.53it/s]

**Comment by psychedelicious** [comment]
I suppose MPS is interfacing with the video card for you. What I should have said is that pytorch does not support AMD video cards on macOS: https://pytorch.org/get-started/locally/

**Comment by FreeBlues** [comment]
> > > My macbook pro 2020 is Intel CPU, with an outside GPU(RX 6600XT 8G VRam). However, it seems that all macOS uses the mps-based code handling process. I usualy use the ddim and 20 steps, and the resulting image looks pretty good.
> > 
> > 
> > Unfortunately macOS is stuck on MPS. There is no support for AMD graphics on macOS at all, so your GPU goes unused :(
> 
> This isn't totally true. I have an Intel Mac with a Radeon 6900XT. Im running the latest pytorch 1.13.0 and I am using the GPU just fine. Its not as fast as when I boot into linux and use ROCm drivers but it does work. To get a 512x512 50step image it takes roughly 30sec in MacOSX, same machine booted in linux will take about 7sec per frame.
> 
> at startup I see:
> 
> > > Using device_type mps
> 
> generating I see:
> 
> > > Sampling with k_euler_ancestral starting at step 0 of 50 (50 new sampling steps)
> > > 100%| | 50/50 [00:32<00:00,  1.52it/s]
> > > Image generated: "/Users/brad/InvokeAI/outputs/img-samples/001012.3885546993.png|| 50/50 [00:32<00:00,  1.53it/s]

It seems that I need to use a docker with Linux image, 30s vs. 7s on your 6900XT, maybe it will be 260s vs. 65s on my 6600XT, or upgrade my video card.

**Comment by psychedelicious** [comment]
Closing as this is more a discussion of system specs and speed.

**Comment by kakajansh** [comment]
Found this on [discord](https://discord.com/channels/1020123559063990373/1050123398342250526/1097000479050960986). On my Macbook M2 Pro, this change affected my generations from 3-7 minutes to under 1 minute 

> Try adding the following options to invokeai.init: 

```
--max_loaded_models 1
--no-nsfw_checker
--free_gpu_mem
--sequential_guidance
```

> And keep your memory usage from other apps to a minimum.
Since that 16 gigs is both your system RAM and your VRAM, and invoke only works in fp32 on MPS, the memory is pretty tight.
