### ISSUE TITLE
[enhancement]: Merging Checkpoints!?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Greetings, as the number of models is increasing at a rapid pace. Merging models seems to be a no brainer.  Such a functionality would be very practical.

Thank you,

### Alternatives

I heard [AUTOMATIC1111 ](https://github.com/AUTOMATIC1111/stable-diffusion-webui) has a similar feature but I couldn't find the documentation yet.

**Comment by discordinated** [comment]
I have automatic1111 running locally just for this feature. I then bring the resulting model back into Invoke and list it in the models yaml. Would love Invoke to have this ability natively.

**Comment by Humanoidme** [comment]
@discordinated i assume you're running automatic1111 locally on PC/Windows or Linux ? I've been trying to find out if it can run on M1s, so far, all attempts have been unsuccessful. Invoke worked though and very happy!

**Comment by FreeBlues** [comment]
@Humanoidme automatic1111 can run on my MBP, after modify some line, but it is too slow(although the usage of GPU is more higher than invokeai, but the speed is about 1/10 of invokeai), I am using an eGPU, I think it can run on M1 too, you can try

**Comment by discordinated** [comment]
> @discordinated i assume you're running automatic1111 locally on PC/Windows or Linux ? I've been trying to find out if it can run on M1s, so far, all attempts have been unsuccessful. Invoke worked though and very happy!

I'm running it on a M1 Max 32GB - To get it running I just followed their[ install guide,](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Installation-on-Apple-Silicon) it was reasonably painless. 

It's much slower than Invoke as FreeBlues has said, and many of the extra functions do not work on MPS. For example last I checked LDSR wasn't working and would crash due to hard coded Cuda calls. I'd LOVE To see Invoke add in LDSR - for now I fall back to doing that on [Colab using this notebook. ](https://colab.research.google.com/drive/19euI_7GAgbvMoZsuPj9SZseDeuFnwBj8#scrollTo=5bA3Tq74zU-w)

I don't use automatic1111 day to day, mostly due to poor performance and the bugs on MPS. Certain things it does do great or I can't get elsewhere however, like merging. But I don't need to do that very often, so at most I check back in once a week or so. Invoke is just so much nicer to use - both visually as well as in terms of workflow and performance.

**Comment by hipsterusername** [comment]
There are ambitions to serve the full set of usecases w.r.t. training (textual inversion overhaul, dreambooth, etc.) and managing models. 

There's a significant architecture overhaul we're in the process of executing on, and after which I think will have time to dig into this space, but I think we'd also benefit from a contributor who is very knowledgeable about this domain to tackle it.

**Comment by Humanoidme** [comment]
@discordinated @FreeBlues thanks to both for taking time to share your insights and knowledge

**Comment by lstein** [comment]
I've got two model feature enhancements in mind for the development branch. The first is to establish a folder in which you can place .bin files from textual inversions and have a searchable library of prompt keywords that you can use with them to add particular subjects and styles. 

The second is model merging. This will probably be a script that runs outside of either the CLI or the GUI at first. The challenge for me is that I don't know how to do model merging just yet!

I'll start working on these things after the release, so sometime later this week or next.

**Comment by victorca25** [comment]
You need help with model merging? I can help if you want

**Comment by Neosettler** [comment]
@lstein
