### ISSUE TITLE
[bug]: generated images differs from version prior to 2.1

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

Comparing images from earlier version have a delta that is significant. @lstein is this related to the noise jumping from one algorithm to another? In any case, I'd like to know how to re-generated the exact same results has before. Hopping this is still an option.

thank you,

**Comment by lstein** [comment]
Are you using the k* samplers? If so, you can get to the old behavior by
setting --karras_max=1000, or --karras_max=0, depending on which older
version you are comparing to.

**Comment by Neosettler** [comment]
thank you for your input, several thousands of generated images with various samplers later, all metadata need to be updated to the new behavior.

Would you mind elaborating on "depending on which older version you are comparing to"? What value does what and from which previous versions?

Also, --karras_max=1000, or --karras_max=0 doesn't seem to be doing anything different on k* samplers on my side. Could anyone validate this?

**Comment by Neosettler** [comment]
While this is not an issue for newly generated images, going back to previous generated images may be completely different. This issue should be considered as important as it breaks backward compatibility.

**Comment by Neosettler** [comment]
here is a example, while this one is quite subtle, in some cases, it makes a third arm popping up or a completely different image compared to version 2.0.

![stable-diffusion-2022-11-09-230636-209505635](https://user-images.githubusercontent.com/4521415/200998473-f684535a-d50e-4258-a8fa-3d89dce2048e.png)
![stable-diffusion-2022-11-07-154528-209505635](https://user-images.githubusercontent.com/4521415/200998476-614908b7-8c1c-49f0-9e93-765604b46671.png)

Is it possible to get previous behavior back? AFAIK, turning off the noise schedule?

**Comment by lstein** [comment]
If you set the `--karras_max` option on the command line when you start the script, then it will take effect on prompts that don't specifically have that option in the metadata, so you will have the old behavior back.

I can't advise you whether karras_max should be set to 0 or to 1000, because you haven't told me what version of InvokeAI you generated the old images from. At one point karras was turned off for everything, at another point karras was turned on for everything, and then we came up with a threshold at which it gets turned off selectively.

**Comment by Neosettler** [comment]
Thank you [lstein](https://github.com/lstein), I've used: 1.14 and 2.0 prior to 2.1.

I wish it would be that simple but in every cases, karras_max set to 0 or 1000 doesn't bring back the old behavior. My guess is that something other than the noise schedule might be causing the delta.

PS: I've sent you a use case on Discord.

**Comment by ebr** [comment]
I also found some discrepancy between generations; this happened around the 2.1.3 release. I don't know enough about the internals to pinpoint what the root cause might be. Posted about it on Discord: https://discord.com/channels/1020123559063990373/1020123559831539744/1041613576537915432

from left to right (`[date] branch`), but unfortunately I don't have the record of specific commits I had checked out: 
- left: `[2022-11-12] release-candidate-2-1-3` 
- middle: `[2022-11-13] release-2-1-3`
- right: `[2022-11-14] main`

![](https://media.discordapp.net/attachments/1020123559831539744/1041614155246997546/discrepancy.png?width=2856&height=952)

SD 1.5 model used in all cases.

```
{
  "prompt": [
    {
      "prompt": "a futuristic cyberpunk flying vehicle, vaporwave palette, disco lights, bokeh, streets of a futuristic metropolis, crowds looking up, wide-angle action shot, style of Hiroaki Takahashi art ultra perfect composition 3d liquid detailing fluid acrylic by greg tocchini james gilleard joe fenton kaethe butcher Bosch Dan Mumford, Kandinsky art style [collage] [splatter] [streak] [crop] [cut]",
      "weight": 1
    }
  ],
  "steps": 35,
  "cfg_scale": 11,
  "threshold": 12.1,
  "perlin": 0.05,
  "height": 1024,
  "width": 1280,
  "seed": 3724352344,
  "seamless": false,
  "hires_fix": false,
  "postprocessing": [
    {
      "type": "esrgan",
      "scale": 4,
      "strength": 0.75
    }
  ],
  "sampler": "k_lms",
  "variations": [],
  "type": "txt2img"
}
```

**Comment by lstein** [comment]
Just to let you know that I'm still investigating. If you've gained any insights, please let me know.

**Comment by Neosettler** [comment]
I've noticed that the "precision" also have an effect so it is important when comparing version that the "precision" is the same.
