### ISSUE TITLE
[bug]: Safety checker and CUDA OOM

### ISSUE THREAD

**Issue by rupeshs** [invoke-ai/InvokeAI#1448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

Start invoke.py with --safety_checker (Tested on RTX 3060,6GB).

Prompt :
`invoke> a fantasy landscape --width 768 --height 512`

It will not generate image and raises CUDA out-of-memory error. Please see the attached screenshot.

### Screenshots

![safety-cuda-oom](https://user-images.githubusercontent.com/3255994/201368794-84725bb2-7cdb-47ff-9df1-5499df776e00.PNG)

**Comment by addianto** [comment]
I guess it is because your GPU run out of VRAM. I also experienced the same issue when I enabled `safety_checker` option. Mine is using GTX 1660.

Enabling `safety_checker` seems increased the total VRAM used. If you do need to use `safety_checker`, then you may try to close as many apps as possible that consume VRAM and hope the remaining VRAM is enough to run the model + safety checker. Or, switch to higher capacity GPU with larger VRAM.

**Comment by psychedelicious** [comment]
Closing as this is just a system resources issue, nothing we can do.
