### ISSUE TITLE
[bug]: UI: Upscale parameters are not loaded from an image

### ISSUE THREAD

**Issue by ebr** [invoke-ai/InvokeAI#1472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16

### What happened?

Repro case:

1. run a prompt, any prompt, with upscale OFF
2. run same prompt with upscale ON
3. right click the first generation and "Use all parameters"
4. upscale remains ON, whereas it should turn OFF

try to change any other parameters; they are reloaded as expected from any generated image. Except upscale, in either direction

### Contact Details

discord: brodsky

**Comment by psychedelicious** [comment]
Sorry for the late response here.

This is intentional. An image may be post-processed an arbitrary number of times, but we cannot tell the UI (or the backend) to do that programmatically. The most we can do without providing a very inconsistent user experience is recall the generation-specific parameters. 

In the future when we roll out the node graph processing API, this will feasible.

The post-processing parameters can be recalled individually.
