### ISSUE TITLE
[bug]: Black square on Docker for Mac

### ISSUE THREAD

**Issue by santisbon** [invoke-ai/InvokeAI#1524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cpu

### What happened?

When running a Linux container on macOS, the generated image is always a black box. 

I'm using these env vars as this is Docker running Linux containers on an arm64 (aarch64) Mac M2:
ARCH=aarch64
INVOKEAI_CONDA_ENV_FILE=environment-lin-aarch64.yml

I'm using the run.sh script with no parameters. The web UI starts up and seems to work fine at first, I don't see errors on the web UI console or on the running container's logs. When it's finished, the image saved to the docker volume is a black square.

### Additional context

The local installation on macOS is working fine, the issue happens only on Docker.

**Comment by mauwii** [comment]
As pointed [out in the Docs](https://invoke-ai.github.io/InvokeAI/installation/INSTALL_DOCKER/) you should not use the Container with Apple M1/M2 since you cannot mount the GPU. It can be helpful for development tasks, but when u rly want to create images, there is a difference of 8+ seconds per Iteration.

Besides that, when I was fixing the Dockerfile today, I did a succesfull Test but I was using the development Branch. This is my .env file which I used when running `build.sh`/`run.sh` scripts:

```
HUGGINGFACE_TOKEN=***
ARCH=aarch64
INVOKEAI_CONDA_ENV_FILE=environment-lin-aarch64.yml
INVOKEAI_BRANCH=development
```

**Comment by santisbon** [comment]
Yes, I'm aware of that GPU limitation (I wrote a good part of that documentation). But it used to work on Linux containers on Mac before the GFPGAN refactoring. Since #614 is marked as closed and there's now a linux arm64 conda file I was hoping it would be working with the latest version on main. Can you confirm if your successful test on the development branch was done with a macOS host?

**Comment by mauwii** [comment]
Scusi, yes, also Apple M1 User here 🙈

**Comment by santisbon** [comment]
Cool, I'll give it a try with the dev branch. If that's working we're probably close to seeing this issue fixed once and for all!

**Comment by mauwii** [comment]
since there was no more message and it is working on my site I will close this issue
