### ISSUE TITLE
[bug]: Patchmatch error (development Branch)

### ISSUE THREAD

**Issue by mickr777** [invoke-ai/InvokeAI#1577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12gb

### What happened?

Just Fyi text when starting invoke.py, all still loads fine after the error
```
Compiling and loading c extensions from "/venv/lib/python3.10/site-packages/patchmatch".
find: ‘csrc/’: No such file or directory
find: ‘csrc/’: No such file or directory
rm -rf build/obj libpatchmatch.so
find: ‘csrc/’: No such file or directory
find: ‘csrc/’: No such file or directory
find: ‘csrc/’: No such file or directory
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
[link] libpatchmatch.so ...
g++: fatal error: no input files
compilation terminated.
make: *** [Makefile:44: libpatchmatch.so] Error 1
```

**Comment by Vargol** [comment]
This situation is worse in macOS, patchmatch assumes a pkg-config environment

Compiling and loading c extensions from "/Volumes/Sabrent Media/Documents/Source/Python/InvokeAITest/lib/python3.10/site-packages/patchmatch".
find: csrc/: No such file or directory
find: csrc/: No such file or directory
rm -rf build/obj libpatchmatch.so
find: csrc/: No such file or directory
find: csrc/: No such file or directory
find: csrc/: No such file or directory
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing ``opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing ``opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
[link] libpatchmatch.so ...
clang: error: no input files
make: *** [libpatchmatch.so] Error 1

**Comment by Vargol** [comment]
find: csrc/: No such file or directory

These errors are fixed in the Invoke patchmatch repo, but the environment and requirements files are set to clone a earlier tagged version,

The pkg config issues are more complicated.

From the discussion on discord

Looks like the windows binary is using opencv 4.6.0 which  macport actually sticks its pc file in 
.../lib/opencv4/pkgconfig  not .../lib/pkgconfig (... for macports is /opt/local, for brew its something with Cellar in it,  for linux is probably  /usr/local unless they've changed things over there 🙂  )

Its also called opencv4.pc not opencv.pc, so at least for me its looking in the wrong place for the wrong file. I'll brute force a quick fix for that, by softlinking the pc file and setting PKG_CONFIG_PATH as see what I get (edited)

After
Installing opencv 4.6.0 using  macports.
Manually uninstalling  patchmatch and re-installing the HEAD version
Setting PKG_CONFIG_PATH  to /opt/local/lib/opencv4/pkgconfig
Soft linking  . /opencv4.pc  to opencv.pc in /opt/local/lib/opencv4/pkgconfig  

I think I got it working with some warning about duplicate symbols in opencv's libs and the opencv abi library in the pip opencv install e.g.

`objc[12125]: Class CaptureDelegate is implemented in both /Volumes/Sabrent Media/Documents/Source/Python/InvokeAITest/lib/python3.10/site-packages/cv2/cv2.abi3.so (0x15aece480) and /opt/local/lib/opencv4/libopencv_videoio.4.6.0.dylib (0x28afa1150). One of the two will be used. Which one is undefined.
`

**Comment by keturn** [comment]
Is this a compilation step we're going to be able to do during packaging and include in the installation?

Or is it something that _has_ to happen at runtime on the target environment?

cuz requiring opencv build-deps at runtime seems like a lot

**Comment by lstein** [comment]
The missing Makefile and `csrc` is addressed in https://github.com/invoke-ai/InvokeAI/pull/1580. However, correct installation is still dependent on libopencv being installed. On Ubuntu, the user will need to install the `apt` packages  `libopencv-core4.2`
