### ISSUE TITLE
[bug]: Settings not being copied when using "Use all parameters"

### ISSUE THREAD

**Issue by apfelnymous** [invoke-ai/InvokeAI#1579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux, Firefox

### GPU

cuda

### VRAM

6GB

### What happened?

img2img strength and restore face settings are not being copied when using "Use all parameters"

**Comment by psychedelicious** [comment]
Face restore is expected, img2img fixed in upcoming release.

Postprocessing metadata cannot be recalled because we can have an arbitrary number of postprocessing steps in the metadata but cannot recall an arbitrary number of steps. So we have decided to not give a false impression that postprocessing steps can be recalled.
