### ISSUE TITLE
[bug]: InvokeAI is sometimes installed in C:\Windows\system32

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#1694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What happened?

InvokeAI is installing to in system32 for some users.

I do not have windows to test, but I *think* what is going on is that when you double click a .bat file, cmd sets the current working directory not the .bat file location, but the location of cmd, which is C:\Windows\system32.

This is just a suspicion, and we need Windows users to attempt to recreate this (I do not have windows available to me).

**Comment by psychedelicious** [comment]
Another user believes this happened when they ran the batch file as Administrator. Maybe that is the cause.

**Comment by theubie** [comment]
I can confirm.  Just tried to do the install by double-clicking on the install.bat file.  Had a lot of file permission issues.  Decided to run the install.bat file as admin, most of the install went to the folder I was running from, however, .venv was created in system32 along with several other supporting files since the bat file was run with elevated privileges.  It looks like at least part of the install batch file thinks it is being run from system32.  I remember it asking where to install the models, and it defaulted to the system32 folder.  I manually changed that to the folder I was trying to install from and had no issues downloading the models.  After it said it was complete, the invoke.bat file was not there.  Manually copying the invoke.bat file and renaming it resulted in file not found because .venv was in system32 and not the folder I did the install in.

Scrubbed the entire directory and started again from scratch, this time running from the command prompt instead of from the windows gui.  Same result.

Windows 11, for the record.  I'd assume the same would happen on Windows 10.
