### ISSUE TITLE
WebUI will not load; only HTML is displayed

### ISSUE THREAD

**Issue by zvit** [invoke-ai/InvokeAI#1811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

10GB

### What happened?

As can be seen in the screenshot, InvokeAI WebUI will not load. It displays only HTML. I have tried the following tests and things so far:

1. As well as a manual installation of InvokeAI, I also tried two different versions of a one-click installation.
2. I have tried on five browsers. My five different browsers are all up-to-date, cache cleared, and allow JavaScript for 127.0.0.1:9090.
3. Using NetLimiter, telnet, etc., I ruled out a port issue; port 9090 is open.
4. The 9090 port has been added to my Windows firewall as an "allow" rule. (I also tried while disabling the firewall)
5. My HOSTS file is clean.
6. SD A1111 WebUI works fine on port 7860, so I changed "self.port = args.port" to "self.port = 7860" in backend/invoke_ai_web_server.py, and the command window shows that InvokeAI was loaded on port 7860, but the same HTML issue persists.
7. InvokeAI has been installed with a new Hugging Face token.

I am out of ideas.

### Screenshots

This is what the result looks like:

![chrome_98FRsmPauG](https://user-images.githubusercontent.com/9898388/205700992-e7992ada-a755-41cc-acb9-d27a5278d81d.png)

### Additional context

>>>>
***UPDATE: 12-7-2022 13:46PM***

I switched back and forth between user profiles while testing, **and suddenly it worked on my account!** It worked for a while, but then stopped working again after one more switch. The fact that it worked even once tells me it can be fixed.

>>>>
***UPDATE: 12-7-2022 14:57PM***

After more testing, and switching between user accounts, for the first time in three days, now it's not working in the TEST account either.
>>>>

***UPDATE: 12-9-2022 07:57AM***

After more testing, and switching between user accounts, It worked once on both accounts, but when I closed the server and restarted it, it didn't work again.
>>>>

### Contact Details

ztwersky@gmail.com

**Comment by DenchPokepon** [comment]
**OS**
Windows

**GPU**
cuda

**VRAM**
8Gb

**What happened?**
Same problem, the application sometimes partially loads when you restart it right during the page load, but it does not fully function.

**Comment by samurainate** [comment]
OS
Windows

GPU
cuda

VRAM
6Gb

What happened?
Same result, only on localhost windows machine.  

Addtional info:
Started on first restart after a crash caused by misuse of swap with img2img and an invalid s_end parameter.  Tested FirefoxWeb browser does not affect the result, both firefox and

**Comment by DenchPokepon** [comment]
Some additional info on debugging this issue. Invoke CLI works fine, it produces images from promt, other models as gfpgan work fine. I think, this issue is related to backend (flask websocket or something) or frontend. On first load of localhost:9090 app loads instantly, but <div root> is completely empty so there is no interface at all. Аfter page refresh it starts to refresh infinitely. In debug network tab it starts to load some files like polyfills.1ff60148.js (not the only one), the time column on this item says "pending" infinitely but at the same time, I can access this file directly with http://localhost:9090/assets/polyfills.1ff60148.js. 

App can still be loaded by relaunching invoke.py --web while trying to connect to localhost:9090 in browser but I can't fully understand how to replicate it properly every time, sometimes it works, other times it doesn't. Even if html and js of app loads, app still doesn't function properly. I can send prompts and get images in return, but returned images are blurry in the web interface (not in output folder though). Also unified canvas just doesn't work, I can create some images on it, but than they just dissapear from canvas after generation.

**Comment by samurainate** [comment]
I found a workaround while checking for blocked content.  I have uBlockOrigin in Chrome, and I can see when I load the page all the get and xhr requests show flask is working and running keepalive calls every second.  No content or scripts are blocked by policy, but using the reload function in uBlockOrigin extension causes the web UI to load and render properly for me reliably.  I don't know how to troubleshoot further, but am happy to do testing or capture logs if someone can give instructions.

**Comment by DenchPokepon** [comment]
> I found a workaround while checking for blocked content. I have uBlockOrigin in Chrome, and I can see when I load the page all the get and xhr requests show flask is working and running keepalive calls every second. No content or scripts are blocked by policy, but using the reload function in uBlockOrigin extension causes the web UI to load and render properly for me reliably. I don't know how to troubleshoot further, but am happy to do testing or capture logs if someone can give instructions.

samurainate, thanks for the clue!
I fixed the app, everything works great. The problem was in kaspersky port handling which doesn't even turn off when you turn off kaspersky. 

It's all about this setting. If it's turned off (don't forget to restart browser) then everything starts working
<img width="750" alt="image" src="https://user-images.githubusercontent.com/60510643/208225860-9cde4d60-0737-495d-8566-97068a8a8465.png">

**Comment by samurainate** [comment]
A little more info.  I turned on the --web_verbose and watched the log.  I don't know if I learned anything useful, but I observed different sequences of events between running clients and the newly launched non-rendered client on localhost, and the point in the logs when it rendered.

Other running clients on the network connected first.  here's the initial log of a good working session from an apple device with the web UI loaded in an active tab when the server started.

```
    jnJIqB_HNcI_h5SPAAAA: Sending packet OPEN data {'sid': 'jnJIqB_HNcI_h5SPAAAA', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 100000}
    jnJIqB_HNcI_h5SPAAAA: Received packet MESSAGE data 0
    jnJIqB_HNcI_h5SPAAAA: Sending packet MESSAGE data 0{"sid":"UDDxBDl1Y_6_35DRAAAB"}
    jnJIqB_HNcI_h5SPAAAA: Received request to upgrade to websocket
    jnJIqB_HNcI_h5SPAAAA: Upgrade to websocket successful
    jnJIqB_HNcI_h5SPAAAA: Received packet MESSAGE data 2["requestSystemConfig"]
```

This session upgrades the websocket before requesting system config.  I don't know what this means, but I note it because the localhost windows/chrome browser session in the next log didn't log the websocket upgrade until the time when I pressed refresh and the UI rendered correctly for the first time.

Here's the localhost session logs for the windows/chrome device where InvokeAI is running

```
    BC2JSMoFOe1NM3YiAAAE: Sending packet OPEN data {'sid': 'BC2JSMoFOe1NM3YiAAAE', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 100000}
    BC2JSMoFOe1NM3YiAAAE: Received packet MESSAGE data 0
    BC2JSMoFOe1NM3YiAAAE: Sending packet MESSAGE data 0{"sid":"n0Y1LjGWpuG4rT9WAAAF"}
    BC2JSMoFOe1NM3YiAAAE: Received packet MESSAGE data 2["requestSystemConfig"]
    BC2JSMoFOe1NM3YiAAAE: Sending packet MESSAGE data 2["systemConfig",{"model":"stable diffusion","model_weights":"waifu-diffusion-1.3","model_hash":"a16d2f57b229156a61ccab6b1cbc120332f3a2a320c75952241e6439f3fe79ec","app_id":"invoke-ai/InvokeAI","app_version":"v2.2.4","model_list":{"stable-diffusion-1.5":{"status":"not loaded","description":"The newest Stable Diffusion version 1.5 weight file (4.27 GB)"},"inpainting-1.5":{"status":"not loaded","description":"RunwayML SD 1.5 model optimized for inpainting (4.27 GB)"},"waifu-diffusion-1.3":{"status":"active","description":"Stable Diffusion 1.4 fine tuned on anime-styled images (4.27)"},"mdjrny-v4":{"status":"not loaded","description":"Midjourney Style, keyword mdjrny-v4 style"},"stable-diffusion-1.4":{"status":"not loaded","description":"The original Stable Diffusion version 1.4 weight file (4.27 GB)"},"trinart-2.0":{"status":"not loaded","description":"An SD model finetuned with ~40,000 assorted high resolution manga/anime-style pictures (2.13 GB)"},"trinart_characters-1.0":{"status":"not loaded","description":"An SD model finetuned with 19.2M anime/manga style images (2.13 GB)"},"papercut-1.0":{"status":"not loaded","description":"SD 1.5 fine-tuned for papercut art (use \"PaperCut\" in your prompts) (2.13 GB)"},"voxel_art-1.0":{"status":"not loaded","description":"Stable Diffusion trained on voxel art (use \"VoxelArt\" in your prompts) (4.27 GB)"}},"infill_methods":["patchmatch","tile"]}]
    BC2JSMoFOe1NM3YiAAAE: Received packet MESSAGE data 2["requestImages","result",null]
    BC2JSMoFOe1NM3YiAAAE: Sending packet MESSAGE data 2["galleryImages",{"images":...omitted long message...k_heun","width":512,"height":640,"category":"result"}],"areMoreImagesAvailable":false,"category":"result"}]
    BC2JSMoFOe1NM3YiAAAE: Received packet MESSAGE data 2["requestImages","user",null]
    BC2JSMoFOe1NM3YiAAAE: Sending packet MESSAGE data 2["galleryImages",{"images":[],"areMoreImagesAvailable":false,"category":"user"}]
    BC2JSMoFOe1NM3YiAAAE: Received request to upgrade to websocket
    BC2JSMoFOe1NM3YiAAAE: Upgrade to websocket successful
    BC2JSMoFOe1NM3YiAAAE: Sending packet PING data None
    BC2JSMoFOe1NM3YiAAAE: Received packet PONG data
    BC2JSMoFOe1NM3YiAAAE: Sending packet PING data None
    BC2JSMoFOe1NM3YiAAAE: Received packet PONG data
    BC2JSMoFOe1NM3YiAAAE: Sending packet PING data None
    BC2JSMoFOe1NM3YiAAAE: Received packet PONG data
```

The sequencing is different to the apple session, no idea if it's a meaningful difference or not.  What's not apparent is the timing since there are no timestamps here.  I watched side by side while refreshing to get the UI to render.  The messages requesting system config and images occurred while the web UI was still rendering a blank page.  This time a regular browser page refresh triggered the normal web UI to render without using the uBlockOrigin extension interface.  That is also when the request to upgrade websocket messages occurred in my side by side view.

**Comment by samurainate** [comment]
> > I found a workaround while checking for blocked content. I have uBlockOrigin in Chrome, and I can see when I load the page all the get and xhr requests show flask is working and running keepalive calls every second. No content or scripts are blocked by policy, but using the reload function in uBlockOrigin extension causes the web UI to load and render properly for me reliably. I don't know how to troubleshoot further, but am happy to do testing or capture logs if someone can give instructions.
> 
> samurainate, thanks for the clue! I fixed the app, everything works great. The problem was in kaspersky port handling which doesn't even turn off when you turn off kaspersky.
> 
> It's all about this setting. If it's turned off (don't forget to restart browser) then everything starts working <img alt="image" width="750" src="https://user-images.githubusercontent.com/60510643/208225860-9cde4d60-0737-495d-8566-97068a8a8465.png">

I am not running Kaspersky, and I don't have anything intercepting and modifying web traffic that I know of.  I'll look around.  Refreshing is still only a workaround, first load is always a blank page.

**Comment by samurainate** [comment]
Quick update, I found a script call to github.com from localhost was blocked by uBlockOrigin, causing the load of the WebUI to fail.  I'll look for the source of the call when I next have time.

**Comment by zvit** [comment]
> Quick update, I found a script call to github.com from localhost was blocked by uBlockOrigin, causing the load of the WebUI to fail. I'll look for the source of the call when I next have time.

OMG, please do! I'm having the same issue with lama-cleaner, and would really like to enjoy WebUIs like everyone else. Please update as soon as you find the script.
