### ISSUE TITLE
[bug]: Image deletion cause Permission Denied  when outdir is on another linux mount point

### ISSUE THREAD

**Issue by ebziw** [invoke-ai/InvokeAI#1855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

10GB

### What happened?

It's a typical linux box with two disks, one is for the system and home dir one is for the data. I put model dir and output dir on the data mount point. Create user dir and assign permission. Everything works fine, but when I try to delete an image, the backend reports a "Permission Denied" problem. It seems it tries to put the deleted image to a "trash" dir one level above the output dir. In my case, it is the "/mnt/output-disk/" dir. However, that dir is not owned by the current user.  It should be something to do with the path calculation for the trashbin.

Can live with it, just comment out the send2trash part, but annoying.

Hope this helps.

### Screenshots

>> Delete requested "outputs/000063.1777ae08.79647714.png"
/mnt/output-disk/liyong3/000063.1777ae08.79647714.png
b'/mnt/output-disk/.Trash-1002'

Traceback (most recent call last):
  File "/home/liyong3/invokeAI/installer_files/env/envs/invokeai/lib/python3.9/site-packages/send2trash/plat_other.py", line 156, in find_ext_volume_fallback_trash
    check_create(trash_dir)
  File "/home/liyong3/invokeAI/installer_files/env/envs/invokeai/lib/python3.9/site-packages/send2trash/plat_other.py", line 95, in check_create
    os.makedirs(dir, 0o700)
  File "/home/liyong3/invokeAI/installer_files/env/envs/invokeai/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: b'/mnt/output-disk/.Trash-1002'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liyong3/invokeAI/backend/invoke_ai_web_server.py", line 700, in handle_delete_image
    send2trash(path)
  File "/home/liyong3/invokeAI/installer_files/env/envs/invokeai/lib/python3.9/site-packages/send2trash/plat_other.py", line 211, in send2trash
    dest_trash = find_ext_volume_trash(topdir)
  File "/home/liyong3/invokeAI/installer_files/env/envs/invokeai/lib/python3.9/site-packages/send2trash/plat_other.py", line 167, in find_ext_volume_trash
    trash_dir = find_ext_volume_fallback_trash(volume_root)
  File "/home/liyong3/invokeAI/installer_files/env/envs/invokeai/lib/python3.9/site-packages/send2trash/plat_other.py", line 159, in find_ext_volume_fallback_trash
    raise TrashPermissionError(e.filename)
send2trash.exceptions.TrashPermissionError: [Errno 13] Permission denied: b'/mnt/output-disk/.Trash-1002'

**Comment by coricarson** [comment]
OK, so here's the deal. There's an easy patch that clears the error message but does the wrong thing in the end, and then there's a better way to solve this.

The issue is caused by the 3PP send2trash, where it doesn't correctly handle nested mount points. It is called by this project at https://github.com/invoke-ai/InvokeAI/blob/c3ff9e6be8beb85bb724e19c7b0d5da24e693f05/invokeai/backend/web/invoke_ai_web_server.py#L878 . 

There is a beta version of send2trash (https://pypi.org/project/Send2Trash/) that catches this exceptional condition and does a file move operation instead of a file rename operation: `1.8.1b0`
https://github.com/arsenetar/send2trash/commit/5e4517aa53fbfc2f93d3c4983bac3a2d4b2c6e89
https://github.com/arsenetar/send2trash/releases/tag/1.8.1b0

HOWEVER, what this is going to do is put the trashes in your data volume holding the models, where the https://github.com/invoke-ai/InvokeAI/blob/main/docker/run.sh won't clean it up. It'd be effectively a disk leak.

---

OK, so what do we do?

The better way to resolve this is to no longer nest the mounts in the first place.

Change this line:
https://github.com/invoke-ai/InvokeAI/blob/main/docker/run.sh#L27
```bash
--mount type=bind,source="$(pwd)"/outputs/,target=/data/outputs/ \
```

to 

```
--mount type=bind,source="$(pwd)"/outputs/,target=/outputs/ \
```


and override the default CMD of the dockerfile to point the output directory to this new location:
```bash
~/InvokeAI/docker$ ./run.sh --web --host 0.0.0.0 --port 9090 --outdir /outputs
```

..... aaaand that's it! Bug resolved.
