### ISSUE TITLE
[bug]: install error

### ISSUE THREAD

**Issue by Nicolas-Formenton** [invoke-ai/InvokeAI#1901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What happened?

Everytime I try to install through the install.bat, it results in the same error (picture below). 

Then I try to open the link and it works normally, maybe the installer is bugging?! Idk, what should I do?!

Also tried manually but when I have to create the virtual environment and then use '''source invokeai/bin/activate''', it seems that I don't have the '''bin''' folder, neither the '''source''' command work.

### Screenshots

![image_2022-12-10_145204147](https://user-images.githubusercontent.com/81488809/206868589-0b352bbe-515a-4daf-bd55-ccf019fd97ca.png)

### Contact Details

nformenton@gmail.com

**Comment by RektException** [comment]
![install](https://user-images.githubusercontent.com/97247877/211452327-4ead31df-27af-45c8-a617-e3282151bd13.jpg)
Me too.
I use a VM, well many. Couldn't install in Debian either because "'cmd' was not defined". It may be because my BIOS requires certain virtualization setting for VirtualBox to work, and it also conflicts with WSL2, so I'm stuck with the first version. but in essence, my hypervisor is turned off to allow VM use. Check if your hypervisor is enabled. and enable it if not. Might help, might not.
