### ISSUE TITLE
[bug]: can't select inpaint model

### ISSUE THREAD

**Issue by Caio-Sc** [invoke-ai/InvokeAI#1929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

Whenever I try to change to inpaint model I get this error "FileNotFoundError: [Errno 2] No such file or directory: 'models\\ldm\\stable-diffusion-v1\\sd-v1-5-inpainting.ckpt'"

**Comment by githubUser01946** [comment]
If you searched you would see that this issue has been mentioned in #1894 

There has been an update since I posted that as you will see in the post below yours: #1925 

I havent updated yet because as mentioned in #1894 I was waiting for a ping to say I could but I am assuming it will fix the error.....assumptions can be wrong though.

**Comment by Caio-Sc** [comment]
thx, sorry for the inconvenience
