### ISSUE TITLE
How to properly uninstall InvokeAI

### ISSUE THREAD

**Issue by if3lc** [invoke-ai/InvokeAI#2004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

---

How can I properly uninstall the invokeai? Is it enough to delete the folder where it is installed?

I forgot to mention im mac user :)

**Comment by Barafu** [comment]
1) Delete the folder you installed into. 
2) Delete the folder in your user profile where models and settings are stored. 

That's all, it does not leave any other trails on the system.

**Comment by if3lc** [comment]
Thanks for the info :) Are all the files in this folder during installation?

**Comment by hipsterusername** [comment]
Yes. You may also want to remove any python installations on your machine.

**Comment by devingfx** [comment]
Hi!
I installed invokeAI on a macOS (but I'm not used to, I'm more a linux user) and before install (od everything including python), I looked at disk occupation, I had 96Go free and after install (including SD1.5 model) I have now 70Go free, so the entire process took 26Go on disk...
If I `du -hs invokeAI` I have got 9,6Go so I wonder where are the other 16Go to remove ?

Could you explain/list all the python stuff location to uninstall ? 
Maybe some temporary files too (because I had a "download models" process been canceled so maybe some stuff still remains somewhere)

Thx
