### ISSUE TITLE
[bug]: WebUI: thumbnails folder seems to never clean

### ISSUE THREAD

**Issue by Barafu** [invoke-ai/InvokeAI#2119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8

### What happened?

I just noticed there are "thumbnails" folder and "temp-images" folder in the "output" folder, that contains small copies of all the images I've generated. Including those that I deleted a month ago. And intermediate steps. And all the junk. 

First, this is a waste of space. 

Second, this may be a breach of privacy. 

Thumbnails for deleted images must also be deleted. Temp images should be cleared both on start and shutdown of the backend. (On the start in case previous launch was a crash).

**Comment by blessedcoolant** [comment]
1. Thumbnails are deleted when you delete an image from the Gallery of the UI. I just tested this on the latest PR and seems to be working as intended. Maybe something bugged out on your end at some point that prevented this from happening for older images.
2. Intermediate images are only saved when you set the preview mode as 'Accurate'. In this case, it is presumed that the user wants to save these intermediate steps for usages such as making a generation video and etc. So we do not delete them. If you do not want to save the intermediate steps to disk, please use the 'Fast' mode for the previews.
3. As for the temp-images, they are created during your work on the canvas. These images are required in order to enable canvas history letting you undo and redo. You are provided with an option on the canvas to delete this temp images. Look under Settings of the Canvas. Do note that clearing temp files will remove the history of your canvas and lose any undo or redo ability.
4. Breach of privacy in what sense? Everything that you do is completely local and offline to your system and not connected to anything.
5. We do not auto clear temp files for the same reason mentioned in point 3. They allow the user to retain undo  history over sessions. This is an extremely useful feature to many. And for those who do not need it, we provided an option to clear.

**Comment by Barafu** [comment]
1: I had checked the folders again, after doing some work. While thumbnails for most deleted files are gone, some stay. I can not understand the logics of when thumbnails are deleted and when they aren't. If I do, I'll add steps to reproduce, here.

3: Temp images are cleared when I press the button on the unified canvas. That is OK. 

4: People share computers more than you think and more than they want to. Silently keeping user files in technical folders should always be avoided.

**Comment by bitfabrikken** [comment]
Still seeing this, and may have found one of the ways the clutter is happening.
To reproduce:

1. Use image to image.
2. Set seed to random and hit Invoke a few times.
3. Observe the images being saved in <invokeai-dir>/outputs/images/
4. Press discard all
5. Images are not deleted, and aren't deleted on exit either.
6. Clear canvas also doesn't delete the images

After a week of using InvokeAI, love it by the way, I had thousands of files that were just in limbo, making a mess and possibly a privacy issue as mentioned.

Invoke 4.2.4 on Linux.
