### ISSUE TITLE
[bug]: How do I uninstall everything you installed? 

### ISSUE THREAD

**Issue by DataJuggler** [invoke-ai/InvokeAI#2154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

23

### What happened?

This wasn't worth the trouble, I just want to make sure I get all this off my system. Does deleting the folder I installed removed everything? None of the pictures were even close to other things I have seen.

Thanks, not sure how this got 9,000 stars.

**Comment by blessedcoolant** [comment]
I think you misunderstand what this software does. This is a toolkit that empowers your usage of Stable Diffusion. We do NOT create any styles, models or images of our own.

At the end of the day, the quality of your results comes down to your prowess with prompt crafting, understanding of the variables at hand that you can tweak to achieve your desired results. The user has complete control over their generations. And if I may say so, I have seen some astonishingly beautiful stuff created with InvokeAI on par with any other toolkit out there. In fact in a lot cases, I personally believe our prompting system allows for easier generation of accurate prompting much more than a lot of the others out there.

And I think the reason we have 9000 stars is probably because a good number of people recognize that. At this current time, I also believe we have one of the best canvas experiences for Stable Diffusion.

Either way, I am sorry you were unable to get what you were looking for. Deleting the folder in most cases should delete everything. You might have to also delete your config folder which is generally in your Users directory (or whichever directory you set during the installation process).

Have a good day.

**Comment by DataJuggler** [comment]
I shouldn’t post anything after a few beers. Will this ever be upgraded to 2.0 Stable Diffusion? Anytime line on that.

**Comment by blessedcoolant** [comment]
Yes. We are making the port to Diffusers. Work is currently underway for that. And with Diffusers comes support for 2.x models.
