### ISSUE TITLE
[bug]: No Model Manager button available.

### ISSUE THREAD

**Issue by CrepuscularDislocation** [invoke-ai/InvokeAI#2220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cpu

### VRAM

8GB

### What happened?

Launching the webui with v2.2.5 doesn't display the Model Manager as shown in screenshots from others.

### Screenshots

<img width="572" alt="Missing Model Manager" src="https://user-images.githubusercontent.com/92269587/210479290-46f29bb5-4970-4a60-874e-78c5a4486749.png">

### Additional context

I had 2.2.2 previously installed and deleted it. I did a fresh install of 2.2.5 because the update process was altered between those versions. I copied some output files to the new installation. I re-installed all my existing models manually, and edited the newly installed models.yaml file.

Functionality is fine, but no Modules Manager.

### Contact Details

redshirtmarkie@yahoo.com

**Comment by washinoboku** [comment]
I had the same problem. It's just that 2.2.5 was the second update. I thought of deleting all the content where I have invokeAI installed except for the ckpt model folder and the ".venv" folder, then I did a clean install and omitted the steps where it downloads the remaining files. I run the bat to start and it's done, problem solved.
Even a problem with the green status text next to the model list was fixed, which showed me a short "command" instead of the corresponding text.
The language selection icon also appeared.

**Comment by gosho84** [comment]
You don't really neet to delete or clear any folders, for solving this problem just lunch update.bat from root /invokeai folder, then lunch server and open locallhost:9090, model manager button must be there. Worked for me.

**Comment by washinoboku** [comment]
> You don't really neet to delete or clear any folders, for solving this problem just lunch update.bat from root /invokeai folder, then lunch server and open locallhost:9090, model manager button must be there. Worked for me.

2.2.5 _was_ my second update using update.bat. If it's not working, maybe there's something broken between versions

**Comment by CrepuscularDislocation** [comment]
Thanks for this tip, I did exactly that (equivalent on Mac).

Scared me for a second when it gave me the option to install models, as I thought it may have nuked that folder, but it was totally fine.

Really appreciate the tip!

**Comment by avviano** [comment]
I did the upgrade via update.bat - yet the model manager button is still missing. This must be a bug...
