### ISSUE TITLE
Cannot use outpainting

### ISSUE THREAD

**Issue by AntouanK** [invoke-ai/InvokeAI#2287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24GB

### What happened?

Whenever I try to outpaint, I get this error.

![2023-01-10_09-59](https://user-images.githubusercontent.com/4569111/211520713-d664859b-d1dd-46a1-bac2-0a5eee4aea5d.png)

this is how the canvas looks

![2023-01-10_09-59_1](https://user-images.githubusercontent.com/4569111/211520768-5c8dafe3-9ed3-4ee2-ba7f-596a0ce873ed.png)

I'm using the docker version of latest invokeai.
Everything else work fine, inpainting, txt2img etc.

### Contact Details

@antouank

**Comment by lstein** [comment]
@Kyle0654 can you have a look?

**Comment by lstein** [comment]
@Kyle0654 can you have a look?

**Comment by Kyle0654** [comment]
@lstein looks like it's inside the autoencoder? It's weird that it's happening during seam paint and not earlier, but I don't have much familiarity with code below inpaint.py.

@AntouanK do you have updated drivers and such? https://github.com/pytorch/pytorch/issues/33134 seems to indicate driver version might be related, though the issue is rather old.

This suggests there may be an issue with cuda support for newer GPUs: https://stackoverflow.com/questions/74303631/runtimeerror-cudnn-error-cudnn-status-execution-failed-while-using-gpu-with-py

**Comment by AntouanK** [comment]
I'm using a docker container for it.
my setup :

OS : Linux 6.1.3-1-MANJARO

GPU : Nvidia RTX 4090

```
❯ nvidia-smi -l
Wed Jan 11 10:40:30 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.78.01    Driver Version: 525.78.01    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
```

and I did a `./docker-build/build.sh` and a `./docker-build/run.sh`

( I build my own version because on the front-end I want the scrollbars visible in the gallery on the right )

**Comment by mauwii** [comment]
Got this resolved after the container updates?
