### ISSUE TITLE
[bug]: UI slows down and lags

### ISSUE THREAD

**Issue by Kivrar** [invoke-ai/InvokeAI#2289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

UI lags

**Comment by Nilohim** [comment]
The exact same happens to me. It occurs when I use the paint and mask brush and gets slower and slower until it is unusable anymore. Reloading the WebUI helps but it is annoying.

**Comment by psychedelicious** [comment]
When it slows down, please try `Clear Canvas History` from the gear icon. This will erase your undo and redo history. Please confirm if this fixes the issue for you. If it does, I will add a setting to reduce the history which should prevent it from ever getting slow.

**Comment by goodguygregg-dev** [comment]
> 
it fixes the issue, setting a max num undo steps would be good

**Comment by Nate82** [comment]
This is still happening on 2.3.5.post2. GPU: RTX 3060 12GB. PC: Windows 10 32GB RAM

It happens in Unified Canvas when I have a decent sized masked area, pretty quickly it starts "lagging" out everything and causing a 3-5 second delay on moving the mouse, using shortcuts, etc. Like it's freezing.

Could it be because the mask constantly flashes? I can hear my PC "thinking" when I have a mask on something because of the constant pixels flashing.
