### ISSUE TITLE
[bug]: No module named 'safetensors'

### ISSUE THREAD

**Issue by MrMondragon** [invoke-ai/InvokeAI#2368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What happened?

After the last update, get an error mentioning No module named 'safetensors' and does not start.

### Screenshots

![image](https://user-images.githubusercontent.com/8009797/213362049-8a37e622-f0bb-427d-85f0-0343c9a8e38f.png)

**Comment by MrMondragon** [comment]
Found a way to solve it: activated the .venv and installed the safetensors lib with pip. Might be usefull to correct the installers, though

**Comment by romandesign** [comment]
I have the same error. How do I fix it on Windows 11 PC?

**Comment by joelnet** [comment]
temp fix:

modify `.venv/pyvenv.cfg`

change this:

```
include-system-site-packages = false
```

to this:

```
include-system-site-packages = true
```

ensure you have safetensors installed:

```bash
pip install safetensors
```

**Comment by curiosus0ne** [comment]
Same issue here on macOS, it happens when Iaunch invoke.sh or update.sh:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/XXX/invokeai/.venv/bin/configure_invokeai.py:43 in <module>                            │
│                                                                                                  │
│    40 transformers.logging.set_verbosity_error()                                                 │
│    41                                                                                            │
│    42 try:                                                                                       │
│ ❱  43 │   from ldm.invoke.model_manager import ModelManager                                      │
│    44 except ImportError:                                                                        │
│    45 │   sys.path.append('.')                                                                   │
│    46 │   from ldm.invoke.model_manager import ModelManager                                      │
│                                                                                                  │
│ /Users/XXX/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/model_manager.py:19 in      │
│ <module>                                                                                         │
│                                                                                                  │
│    16 import time                                                                                │
│    17 import traceback                                                                           │
│    18 import warnings                                                                            │
│ ❱  19 import safetensors.torch                                                                   │
│    20 from pathlib import Path                                                                   │
│    21 from typing import Union, Any                                                              │
│    22 from ldm.util import download_with_progress_bar                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'safetensors'

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/XXX/invokeai/.venv/bin/configure_invokeai.py:46 in <module>                            │
│                                                                                                  │
│    43 │   from ldm.invoke.model_manager import ModelManager                                      │
│    44 except ImportError:                                                                        │
│    45 │   sys.path.append('.')                                                                   │
│ ❱  46 │   from ldm.invoke.model_manager import ModelManager                                      │
│    47                                                                                            │
│    48 #--------------------------globals-----------------------                                  │
│    49 Model_dir = 'models'                                                                       │
│                                                                                                  │
│ /Users/XXX/invokeai/.venv/lib/python3.10/site-packages/ldm/invoke/model_manager.py:19 in      │
│ <module>                                                                                         │
│                                                                                                  │
│    16 import time                                                                                │
│    17 import traceback                                                                           │
│    18 import warnings                                                                            │
│ ❱  19 import safetensors.torch                                                                   │
│    20 from pathlib import Path                                                                   │
│    21 from typing import Union, Any                                                              │
│    22 from ldm.util import download_with_progress_bar                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'safetensors'

**Comment by curiosus0ne** [comment]
> temp fix:
> 
> modify `.venv/pyvenv.cfg`
> 
> change this:
> 
> ```
> include-system-site-packages = false
> ```
> 
> to this:
> 
> ```
> include-system-site-packages = true
> ```
> 
> ensure you have safetensors installed:
> 
> ```shell
> pip install safetensors
> ```

tried that but that didn't help, there are  still issues with safetensors module missing

**Comment by xX-GeoffreyG-Xx** [comment]
Having this same problem when trying to run the "Command Line" option (#1) from `Invoke.bat` on Windows 10.  When I choose option #1 in `Invoke.bat`, it starts to load, but then I get the error message: 

`ModuleNotFoundError: No module named 'safetensors'`

It looks like the problematic code is in file:

`binary_installer\ldm\invoke\model_manager.py:19 in <module>`

The code that is failing is:

`19 import safetensors.torch`

But I don't know why that would be a problem, because the safetensors package has been installed already?!?  However, I'm certainly not an expert in this area or the python code environment.

Per the suggestions above, I tried "pip install safetensors" (again) and that did not fix the problem.  Also tried setting "include-system-site-packages = true" in the `.venv/pyvenv.cfg` file, but that did not work either.  After that, I tried re-running `Install.bat` again, but that didn't help either.

Oddly, running the Web-UI (option #2 in `Invoke.bat`) DOES seem to be working correctly for me.  It would seem that this problem only occurs when I try to run the Command Line option.

Does anyone have any other thoughts about how to fix this problem?

**Comment by ndxf** [comment]
I was having the same problem. It started when I tried to use the update.bat script to update automatically from the install folder. Also, for me the problem persisted even if I tried to start it in webUI mode (option 2 for invoke.bat) instead of console.

An easy fix I found was to launch invoke.bat, choose option 3 (developer console) which took me to the venv console. Here, executing command `pip install safetensors` and then `exit`ing out of the venv console after it finished processing fixed the problem.

I'm not sure why this is happening in the first place, but you guys could try this solution to get around it at the moment. I was able to run update.bat and invoke.bat successfully after this solution.

**Comment by xX-GeoffreyG-Xx** [comment]
@ndxf - Thank you for responding here!  You know what - I didn't mention it in my previous message, but I should have said that this all started when I tried to update to v2.2.5, and I should also mention that I had not updated in a really long time.  So, after I posted this question, I was able to get v2.2.5 re-installed and everything working correctly by taking the following steps:

1. Saved a backup of my `InvokeAI\outputs` and `InvokeAI\models` folders (so I wouldn't lose my images or have to re-download my models).
2. Deleted everything in my `InvokeAI` folder.
3. Downloaded v2.2.5 (from [HERE](https://github.com/invoke-ai/InvokeAI/releases/tag/v2.2.5p2)) and extracted everything back into my `InvokeAI` folder. 
4. Copied my `outputs` and `models` folders back into my `InvokeAI` folder.
5. And ran the new `InvokeAI\install.bat` file (and skipped model downloads).

And at this point, I no longer seem to be getting the `ModuleNotFoundError: No module named 'safetensors'` error message - THANK GOD - and I'm very happy to report this issue seems to be fixed for me now!  I suspect that something was not right with my previous installation OR something went horribly wrong during the update process, and that was the true cause of my problems and this error message.

Either way - THANK YOU AGAIN for your notes here!  I'm really glad people still care about, and support, this project!!  I LOVE Invoke AI!!!
