### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by Shokoladina** [invoke-ai/InvokeAI#2384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8gb or 31

### What happened?

Hello,
i've tryed to install invoke on my laptop, and after waiting for more than 1 hour i've go an error 
ERROR: Wheel 'torch' located at C:\Users\MOI\AppData\Local\Temp\pip-unpack-ekeh6i6s\torch-1.12.1+cu116-cp310-cp310-win_amd64.whl is invalid.
Can you help me to fix it.
Thank you.

### Contact Details

fournier_elena@yahoo.com

**Comment by Barafu** [comment]
But did you try to install again? Seems like a simple download failure. 

BTW, in most ex-USSR countries Internet Providers randomly block and unblock random addresses. Net based installers like this are almost guaranteed to fail from time to time because of that. Try again later or use a (different) VPN.
