### ISSUE TITLE
[bug]: A fraction number in prompt causes black image

### ISSUE THREAD

**Issue by Barafu** [invoke-ai/InvokeAI#2399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8

### What happened?

If a prompt contains a fractional number, the whole rendering process produces a black image. Integer numbers cause no problems. If having a fractional number in the prompt is a syntax error, it should be caught before generation - think of poor souls who generate 30 minutes per picture only to find out they accidentally got a number into the prompt. 

`web 20`
![image](https://user-images.githubusercontent.com/6612364/214052615-66a196dc-c94f-43e8-be68-e2f7e7027f2d.png)

`web 2.0`
![image](https://user-images.githubusercontent.com/6612364/214052679-e3bdb80c-5ffe-44ff-994d-22be413325a2.png)

`web 2/0`
![image](https://user-images.githubusercontent.com/6612364/214052814-facf0c0b-b0e4-4d8f-b617-ba826a548f9c.png)

**Comment by TheBarret** [comment]
isnt that because Invokeai is trying to parse the prompt for certain ast-format? such as: `(subject:1.1)`

**Comment by noodlebox** [comment]
The problem is in the way numeric attention values are parsed in the prompt: `2.0` is interpreted as `2` with a weight of `.0`, which is most likely a bug.

This happens similarly for any words in the prompt that end with a decimal point (`.`) followed by some digits, such as `f/2.8`, which is parsed as `f/2` with a weight of `.8`. 

Intentional use of numeric attention values following words are parsed incorrectly as well. The prompt `intricate1.5` is parsed as `intricate1` with a weight of `.5`.

My suggestion would be to change the prompt syntax specification to only allow numeric weights after parentheses to avoid these issues.

**Comment by Barafu** [comment]
The issue still exists.

**Comment by Barafu** [comment]
This is fixed, thanks!
