### ISSUE TITLE
[enhancement]: Support for JAX &  Google TPUs

### ISSUE THREAD

**Issue by adjarar** [invoke-ai/InvokeAI#2452]
### What should this feature add?

Kaggle offers 20 hours of free TPU use, which greatly speeds up image creation (6 sec for 8 images). Huggingface diffusers already offer JAX implementation in their models. I checked their repo and don't think the implementation difficulty of this is high. A matter of changing a few API calls. 

Is there any interest in incorporating this into the main branch? I'd be willing to give it a try myself.

Details can be found here:
https://huggingface.co/blog/stable_diffusion_jax

**Comment by lstein** [comment]
Your offer of help is gladly accepted. Do you need any pointers? We are currently in a transition between ckpt models and diffusers models. Please confine any changes to the diffusers part of the code, as the ckpt part is going to be deprecated and removed.

**Comment by adjarar** [comment]
Great, I'll dive into the code and see what I can come up with. If you have any tips or recommendations, please let me know. I envision a simple setting in options where you can switch between TPU and GPU.

**Comment by keturn** [comment]
At the moment, we have our own subclass of the diffusers pytorch StableDiffusionPipeline: https://github.com/invoke-ai/InvokeAI/blob/371edc993a36e00bc6f5a3598ee5c83cc65b509f/ldm/invoke/generator/diffusers_pipeline.py#L237

and there are a bunch of methods on it. It will take some refactoring to move them to be less dependent on subclassing so it's easier to switch out that pipeline class, but that's not an insurmountable task by itself.

But that only gets you partway there. It might be enough to use other pytorch-based diffusers pipelines, but there is significant use of pytorch in the InvokeAI code, both in the implementations of those subclass methods and elsewhere.

Some of the code, like the stuff that uses the CLIP text encoder, the easiest way would be to leave it in pytorch and run it on CPU, because it's not so computationally expensive.

Other stuff like the cross-attention controls you'll need to come up with a JAX implementation for.

I don't have anything against JAX personally, but I fear maintaining both JAX and PyTorch pipelines in one project would be biting off more than we can chew.

There is another option: While the current diffusers TPU-compatible pipelines are written with Flax, Flax (and JAX) are not the only way to run something on a TPU. You could also investigate using [torch_xla](https://pytorch.org/xla/) to keep the code based on pytorch and execute it on a TPU device.

**Comment by adjarar** [comment]
Thanks for your comment. Looking through the code, I realize I've underestimated the effort it would take. Although it's nice to have, I agree it's probably too much effort to maintain for such a niche use case. I'll look into the torch xla option, but I suspect it's too much of an undertaking for me right now to implement.

Feel free to close this ticket if you don't want it clogging up your backlog, I can always reopen it later.
