### ISSUE TITLE
[bug]: missing environments-and-requirements directory

### ISSUE THREAD

**Issue by SoftologyPro** [invoke-ai/InvokeAI#2499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

N/A

### What happened?

Current requirements.txt has the line
-r environments-and-requirements/requirements-base.txt
but the environments-and-requirements directory was removed from the repository (?) so the required packages are not installed.
Which leads to this error when launching
ModuleNotFoundError: No module named 'ldm'

**Comment by lstein** [comment]
As of 2.3.0 you no longer need to use requirements.txt, and support has been removed for requirements.txt and environment.yaml. 

Instead the software can be installed from PyPi using the following recipe:

```
mkdir invokeai
python -mvenv create invokeai/.venv
pip install InvokeAI
invokeai-configure --root invokeai
```

A slightly more involved version of this is documented in the new README file: https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/020_INSTALL_MANUAL.md . I'm afraid the documentation hasn't gone live yet during the 2.3.0 prerelease phase, which is why you missed it.

Please see the [2.3.0 release notes](https://github.com/invoke-ai/InvokeAI/releases) for more info.

**Comment by SoftologyPro** [comment]
OK, thanks.  Is there an alternate way to run this
configure_invokeai --root invokeai
without having it pause and prompt the user?  I am trying to automate this from Visions of Chaos.  In the past I used
python scripts\preload_models.py --yes
but that does not seem to be available any more?

**Comment by SoftologyPro** [comment]
Or, can we get parameters in configure_invokeai for token, nsfw on/off, recommended, etc?  That would work for me too so I can automate the install for users.

**Comment by lstein** [comment]
Add the parameter `—yes`. This assumes yes for all the interactive questions. There is also an option that inhibits model downloading.
