### ISSUE TITLE
[bug]: Windows 10 always reports 0.00G VRAM used.

### ISSUE THREAD

**Issue by MarcusLlewellyn** [invoke-ai/InvokeAI#2574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

24GB

### What happened?

After image generation, InvokeAI reports VRAM stats on the console. Unfortunately, on windows, this always seems to result in the following:

```>> Usage stats:
>>   2 image(s) generated in 23.86s
>>   Max VRAM used for this generation: 0.00G. Current VRAM utilization: 0.00G
>>   Max VRAM used since script start:  0.00G
```

### Additional context

No one else has complained about this, AFAIK. So another person running on straight Windows 10 reproducing it might be helpful.

Also, to be clear, this is _not_ using WSL.

**Comment by lstein** [comment]
During the startup phase do you see a message indicating that CUDA is active?

**Comment by MarcusLlewellyn** [comment]
@lstein CUDA is definitely active.

**Comment by JPPhoto** [comment]
@MarcusLlewellyn - Let's revisit this issue after 2.3.0 is live. In the meantime, can I give you some python code to run to get me some numbers?

**Comment by JPPhoto** [comment]
@MarcusLlewellyn Interesting! I figured you were using a diffuser model.

As support for checkpoints is going away, I recommend you go ahead and convert your models to diffusers anyway using the built-in conversion functions or find diffusers versions of those models. Since this seems to work in diffusers and the checkpoint code path support is going to be dropped coming up, I'm going to mark this issue as closed.
