### ISSUE TITLE
[enhancement]: The image with the selected area highlighted - how to get full image when masking?

### ISSUE THREAD

**Issue by FurkanGozukara** [invoke-ai/InvokeAI#2647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

furkangozukara@gmail.com

### What should this feature add?

Hello. I am trying to get full image of masked area when using mask feature.

However I don't know how to make it work

What I want is providing a full image like below

image A
![a](https://user-images.githubusercontent.com/19240467/218532761-a8cbd2ad-2282-4bd4-a45c-f4db2eff0a8e.jpg)

Then run mask command like this

!mask "C:\Users\King\Downloads\a.jpg" -tm "clothes" 0.7

Then I want to get below output

image B
![image](https://user-images.githubusercontent.com/19240467/218532921-45683fa3-0526-4347-beb8-041fda625d7a.png)

However I am getting the below outputs

image C
![image](https://user-images.githubusercontent.com/19240467/218532954-add434a1-558e-4e75-8af2-9baadc8fecd3.png)

image D
![image](https://user-images.githubusercontent.com/19240467/218532971-c35f39af-61f1-4b07-916f-992677c59e48.png)

At the very least instead of highlighted output as above, how can I get full output of masked area?
I mean instead of getting image D as transparent / highlighted how to get it full? 

How could I getimage B? What should I look for?

Thank you so much for answers

**Comment by lstein** [comment]
The transparent images show the confidence of the model. It is showing transparency values ranging from 0 (area is not part of the mask) to 1.0 (area is part of the mask). The threshold is applied to the transparency value in order to segment the image into white (not masked) to black (masked). Basically this operation is used to determine the most appropriate threshold to apply to image generation when using inpainting. 

To extract the image the way you want, you need to open up Photoshop (or similar), import the black and white mask, import the original image, and then apply the one to the other.

**Comment by FurkanGozukara** [comment]
> The transparent images show the confidence of the model. It is showing transparency values ranging from 0 (area is not part of the mask) to 1.0 (area is part of the mask). The threshold is applied to the transparency value in order to segment the image into white (not masked) to black (masked). Basically this operation is used to determine the most appropriate threshold to apply to image generation when using inpainting.
> 
> To extract the image the way you want, you need to open up Photoshop (or similar), import the black and white mask, import the original image, and then apply the one to the other.

could invoke ai add that option to the script? how hard it is? I need it automated
