### ISSUE TITLE
[bug]: Errors inpainting in an image that's a single color

### ISSUE THREAD

**Issue by JPPhoto** [invoke-ai/InvokeAI#2886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What happened?

Whether inpainting or masking, Invoke swaps out its generated content for the color of the background on the last step of generation. This is an issue in 2.3.x and on `main` and has been happening (I believe) since 2.2.5.

### Screenshots

[video](https://drive.google.com/file/d/1nMp5Z0F6dH1pewxcTXlGXwRvNLjDuCfx/view?usp=sharing)

**Comment by keturn** [comment]
[watches video]

[totally baffled]

…whut?

trying to reproduce on `main`...

- normal image: works fine
- all-white image: reproduces bug
- various other single-color init images: yes wtf
- jpeg instead of png: yep that too

ah, it must be the color-correction code:

https://github.com/invoke-ai/InvokeAI/blob/8762069b37f996c4a61757e0283bc5d88e275907/invokeai/backend/generator/base.py#L204-L205

takes the mean and standard deviation of the colors in the input image.

So if there is no deviation in color in the input, there's no deviation in color in the output.

That's a problem.
