### ISSUE TITLE
[bug]: wrong version on automatic install (linux) (amd)

### ISSUE THREAD

**Issue by creachec** [invoke-ai/InvokeAI#3083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

amd

### VRAM

8gb

### What version did you experience this issue on?

2.3.3

### What happened?

In the automatic installation of invoke, in the part that installs pytorch, it installs the wrong version (rocm 5.2), and the right one would be version 5.42, as described in the documents

### Screenshots

<a href="https://ibb.co/6YC0tMz"><img src="https://i.ibb.co/JnJjp1V/Screenshot-from-2023-03-31-17-04-15.png" alt="Screenshot-from-2023-03-31-17-04-15" border="0"></a>

**Comment by Void2258** [comment]
We have a related issues with X-formers also getting out of sync with both the automatically installed pytorch and the one grabbed by manually updating with pip, causing them to be disabled. it appears there is no version pinning in effect (or incomplete version pinning) in order to ensure that everything can work together.
