### ISSUE TITLE
Cannot Startup InvokeAI for First TIme: WinError 3/Errno 2

### ISSUE THREAD

**Issue by senorchipps** [invoke-ai/InvokeAI#3096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

2.3.3

### What happened?

Tried starting the browser-based UI for the first time, was met with two error codes.
 
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/chipps/invokeai/outputs
\\intermediates/'
Exception ignored in atexit callback: <bound method BaseReadline.write_history_file of <pyreadline3.rlmain.Readline object at 0x000002560B397580>>
Traceback (most recent call last):
  File "C:\Users\chipps\invokeai\.venv\lib\site-packages\pyreadline3\rlmain.py", line 180, in write_history_file
    self.mode._history.write_history_file(filename)
  File "C:\Users\chipps\invokeai\.venv\lib\site-packages\pyreadline3\lineeditor\history.py", line 100, in write_history_file
    fp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/chipps/invokeai/outputs \\.invoke_history'

**Comment by saddukar** [comment]
Issue is caused by an extra space in the invokeai.init file located in the rood dir of your installation. To fix it, remove the extra space.
For example, the line with the issue in my case was: 
--outdir="D:/InvokeAI-installer-v2.3.3/InvokeAI-Installer/outputs "
The fixed line is:
--outdir="D:/InvokeAI-installer-v2.3.3/InvokeAI-Installer/outputs"
