### ISSUE TITLE
[bug]: Textual Inversion will not start because it can not load weights from checkpoint file

### ISSUE THREAD

**Issue by FilipTrichkov** [invoke-ai/InvokeAI#3197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What version did you experience this issue on?

2.3.4.post1

### What happened?

When I try to start textual inversion training I get the same issue over and over again. Can someone please tell me how this can be fixed? I have attached a screenshot with what I get when i try to start the training. 

### Screenshots

<img width="1284" alt="Screenshot 2023-04-14 133640" src="https://user-images.githubusercontent.com/61379159/232033551-f567e020-72ba-45f0-bcbd-e98ded45fe04.png">

**Comment by lstein** [comment]
What this looks like is what happens when Windows Defender flags one of the files in a `diffusers` model as being a possible trojan and then removes that file. You get a partial load of the model and then a crash when the system tries to load the missing file.

A solution to this is to remove the base model in question entirely, relaunch textual inversion training, and then let the model re-download. Unfortunately I do not know a way of downloading just the missing file.

You also may run into the issue of Defender removing the file again. You might want to deactivate Defender for a period of time or switch to a base model that isn't flagged.

**Comment by FilipTrichkov** [comment]
@lstein Thank you! I did exactly that and it downloaded the model all over again. 
But now I have another problem - CUDA out of memory. I reduced the batch size to 1 and it still comes up with this error. :( 
Would you happen to know how I can fix this as well? Or is my GPU just not equipped enough for textual inversion? 
I have a NVIDIA GeForce RTX 3050 4GB. 
<img width="1280" alt="Screenshot 2023-04-15 134409" src="https://user-images.githubusercontent.com/61379159/232216083-899a7f2b-0036-49e6-907f-80589158baee.png">
