### ISSUE TITLE
[enhancement]: 77 maximum tokens argument switch

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#3263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

@damian0815 Having backward compatibility in mind, --more_tokens (or else) argument would be necessary to toggle this feature on/off.

The reason I'm asking is that, if previously generated images had tokens being discarded, the result image would be completely different. using the same settings (from metadata).

**Comment by schoenid** [comment]
As example, on stable diffusion webui the main limit is 77 tokens, which expands automatically to the next level, if more are used. So about 500 is easy possible ... however, it should not be necessary.

I changed completely to stable diffusion webui, because of that limit in InvokeAI. It's nearly impossible to create the images I want with only 77 tokens.

On the other side, I miss the stability of InvokeAI !!!

**Comment by hipsterusername** [comment]
Users can manually restrict to 77 tokens if desired
