### ISSUE TITLE
[bug]: Accuarte In-Progress doesnt show any "in progress" preview images

### ISSUE THREAD

**Issue by martin951** [invoke-ai/InvokeAI#3290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

10 GB

### What version did you experience this issue on?

2.3.5-rc1

### What happened?

First of all I just want to thank you for providing this tool. The installation took some time but the guide is clear and everything went smooth.

When generating text2img with the accurate in-progress images setting in the unified canvas window, no previews appear at all until the generation is finished.

**Comment by JaysonPhoenix** [comment]
last time i checked (in this version) i had to set it to save as many images as the steps i use in image creation, then it showed the correct in-progress image for each step. but i disabled it again because of course its annoying to have millions of step images saved to the harddrive. did you test that to make sure its just not showing because its not saving more then the final step to narrow the problem down a bit?
