### ISSUE TITLE
[enhancement]: when do we get controlnet?

### ISSUE THREAD

**Issue by JaysonPhoenix** [invoke-ai/InvokeAI#3319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

this thread

### What should this feature add?

since i didnt find anything about this im gonna ask here. **when do we get access to controlnet and its many models**? 

missing lora access and such and missing controlnet were the 2 most important issues for me (and probably for most users) making me keep using automatic1111 or switch between automaticc and invoke for each task (maybe besides composable prompting to get rid of color contamination and such by specifying prompts for areas of the picture), and now that you finally added lora support (its only missing hypernetwork support now but those get used less so its not that important) you gave me half of what i need most, so what about controlnet now? im sure theres no way around adding it so when are we gonna see that? would be more important than nodes tab which of course is a cool thing but only adds ways of handling things and doesnt add actual tools/features like controlnet does. at least thats how it feels to me after trying comfyai which is great for understanding whats going on under the hood but didnt add anything to my work so far if not creating huge combined pictures, while automatic extensions like controlnet or composable prompting adds huge powerful tools). 

what makes invoke stick out is its more modern designed user and noob friendly ui in general and the power of its unified canvas and maybe the use of diffusors (which most probably didnt even know about since theres so few diffusor models floating around yet), and whats making automatic stick out is its modding capabilities through its extensions which can add great tools and power such as controlnet for example which was a game changer for many. while i kind of understand you didnt want to add general extension support that would make invoke just as moddable but also as buggy some of automatics extensions are mandatory now and thus those have to be added as features if not as extensions in invoke since users cant do without em now, just like loras in this version. i love invoke, and while it doesnt have to have every bleeding edge extension that automatic has right when they are released it at least has to adress the most important outstanding extensions available that change much or add much and arent just some buggy cool toy. controlnet and a way of adressing prompting issues like composable prompting extensions do are such outstanding extensions providing solutions for everyday issues everybody has, so please keep looking for such outstanding extensions and add em your way as a feature for invoke as soon as possible so we can stick to invoke if we like it more than automatic or others and dont have to keep switching because invoke is missing too much. adding loras was such a great step, keep rolling ;)

**Comment by RicoRaw** [comment]
Well that was a very well worded request... and very accurate. I agree completely. Invoke is undoubtedly the winner in terms of UI and overall workflow. That workflow gets halted however, when I try to get specific in certain details, like posing. I've been using Invoke less and less for the past 6 weeks due to that one limitation. I'm now only using Invoke for abstract, landscape, concept and non-character images. 
I fully understand how long and hard it is to code certain implementations into software, so I've been patient. I check the dev notes about once a week to see where things are progressing in the project. I just don't get why nodes would be prioritized above ControlNet. From a novice viewpoint it would seem less complicated to integrate ControlNet, but what do I know. 
Anyhow, that's enough ranting from me. Invoke is still a great project and I'm interested to see how it will grow. I'll continue to check in on the project from time to time, and keep my fingers crossed.

**Comment by Void2258** [comment]
Controlnet is coming in the upcoming 3.0 release, and is in fact already working in the non-stable dev builds (in node form; general UI pending). Many features and feature extensibility are coming in the 3.0 release, which is a major refactor, so new work on 2.3 branch is bug-fix only to avoid duplicate/wasted effort.

**Comment by RicoRaw** [comment]
Can't wait. 3.0 sounds like it's going to be a monster update. ControlNet, nodes, new UI overhaul, and more. Invoke for the win. Maybe.

**Comment by hipsterusername** [comment]
Controlnet is in 3.0
