### ISSUE TITLE
[bug]: LoRA filenames don't like periods?

### ISSUE THREAD

**Issue by Fortyseven** [invoke-ai/InvokeAI#3452]
### Is there an existing issue for this?
- [X] I have searched the existing issues

### OS
Linux

### GPU
cuda

### VRAM
24gb

### What version did you experience this issue on?
2.3.5.post1

### What happened?
I have two LoRAs: 
- `bob_dobbs-n47-v1.safetensors` and 
- `bob_dobbs.n47-v1.safetensors`

Same binary. The only difference being the use of a period in the filename.

`withLora(bob_dobbs-n47-v1,0.75)` works (no period), 
`withLora(bob_dobbs.n47-v1,0.75)` does not.

### Contact Details
fortyseven@network47.org

**Comment by addianto** [comment]
According to [LORA feature documentation](https://github.com/invoke-ai/InvokeAI/blob/v2.3/docs/features/LORAS.md#installing-loras), InvokeAI can only recognise LORA files whose filenames contain alphanumeric symbols and underscore. Although this issue seems easy to fix, it will require some modifications to the [prompt parser](https://github.com/damian0815/compel) (see: [`ldm/invoke/conditioning.py`](https://github.com/invoke-ai/InvokeAI/blob/aa1538bd7075fa094ad9e37ec704f6c06c1d06bf/ldm/invoke/conditioning.py#L56)) used by InvokeAI.

**Comment by Neosettler** [comment]
> Although this issue seems easy to fix, it will require some modifications to the prompt parser (see: ldm/invoke/conditioning.py) used by InvokeAI.

@addianto I'd be very interested in a fix to support any OS filenames for LoRA files. Any chance someone would give it a shot?

**Comment by Neosettler** [comment]
For context, it's probably not a big deal for those who have a handful of LoRA files but for managing a library with hundreds or thousands plus, it's a whole different story. Please, consider the "easy fix".

**Comment by hipsterusername** [comment]
LoRA use will no longer be managed with the prompt parsing. We’ll need to test to see if new implementation has similar issue, but is unrelated to this
