### ISSUE TITLE
[bug]: Upgrade failed

### ISSUE THREAD

**Issue by VeyDlin** [invoke-ai/InvokeAI#3498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What version did you experience this issue on?

2.3.5.post2

### What happened?

When I try to upgrade, I get this error

```
ERROR: Invalid requirement: "'invokeai[xformers]"
❗ Upgrade failed
```

I tried two options:
```
║  [1] Update to the latest official release (v2.3.5.post2)                                                        
║  [2] Update to the bleeding-edge development version (main)
```

**Comment by Sniza** [comment]
I have the same problem, same configuration

**Comment by Kellegram** [comment]
Same problem here, I opened the developer console and ran `pip install InvokeAI --force-reinstall` as per instructions in docs (https://invoke-ai.github.io/InvokeAI/installation/010_INSTALL_AUTOMATED/#package-dependency-conflicts) and the issue was not resolved with that either for info. The result of this issue is that the CPU is used instead of the GPU which makes invoke basically unusable. Happy to provide any logs if needed, but I imagine everyone updating will run into this.

**Comment by Kellegram** [comment]
Fixed by running `pip install InvokeAI --force-reinstall` then `pip install torch torchvision --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu117` then `pip install --force-reinstall xformers` 
It still says there are things that I have too high versions of but now the GPU is utilised, I probably created some 'el classico python mess in the venv, but this at least gets you back to work I guess.

**Comment by YesThisIsMe007** [comment]
I still have a problem.

**Comment by QuestionQuest117** [comment]
I have same problem and last suggestion didn't fix it.

**Comment by Kellegram** [comment]
Welp, still works for me after running that, no problems since my comment.

**Comment by hipsterusername** [comment]
Consider updating to 3.0 beta
