### ISSUE TITLE
[bug]: managed to completely kill webui, even after reboot with nodes

### ISSUE THREAD

**Issue by cchance27** [invoke-ai/InvokeAI#3881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.0.0

### What happened?

I was playing with txt-to-img and decided to try out nodes, I had it enabled, but to my dismay the nodes window wasn't auto-populated with the current working project (txt-to-img) so I figured ok, let me try to load the config from txt-to-img into nodes...

I went back to txt-to-img clicked the info button for the image, jump to the nodes json in the image and just save that to a JSON file and loaded the saved jSON over in the nodes view... and the window went grey, like everything... refreshing didn't resolve the issue.

I restarted the entire invokeai and i'm still getting a blank grey screen, in dev console i'm seeing errors, thought due to obfuscation not much it really tells me on what is actually wrong.

### Screenshots

![image](https://github.com/invoke-ai/InvokeAI/assets/13766359/3a945fbc-76a2-41fa-addb-99967069a17a)

### Additional context

The json i saved from txt-to-img that i loaded into nodes that broke everything :) https://[pastebin.com/raw/XBMEWQTC](https://pastebin.com/raw/XBMEWQTC)

**Comment by cchance27** [comment]
I did manage to get the webui to load, I had to force clear the local-storage for the nodes in the browser for the local url, and that got me back into the UI... I then attempted to reproduce by loading the json again, and sure enough it killed the interface, so apparently somewhere in the json import i think someone forgot to sanitize the imported json, and when it fails the whole interface fails.

What i cleared...
![image](https://github.com/invoke-ai/InvokeAI/assets/13766359/17547bf4-00f5-4538-a896-91e08b255ef8)

**Comment by psychedelicious** [comment]
The JSON in the image isn't the JSON that is loaded to load a graph. You need to use the save button after creating a graph to save it.

We haven't built the logic to parse the graph just yet. We'll be sure to provide a smooth experience loading an image's graph - like a simple "Use this image's graph" button - when we polish the node editor.

**Comment by psychedelicious** [comment]
I'm closing this as non-issue but happy to continue the conversation if you have any questions

**Comment by cchance27** [comment]
How’s this not an issue? It’s not just that importing the json from the image info that doesn’t work it’s that theirs no sanity check in the imported json in the node import…

My issue wasn’t that it didn’t support the json I imported the bug report is that importing invalid json breaks the whole web interface and requires diving into development console to restore any part of the dashboard.

I know it’s experimental so getting changed a lot before going to full release, but still feel their should be a tracked bug or outstanding issue of the fact that invalid json imported crashes the full ui.

It also feels odd to dump the json in the image info that doesn’t match the json that would be used in the nodejs having json displayed and saved differently seems… confusing to the user either the json in the image info should note it’s not for node usage or it should just be properly formatted per node usage.

Also some form of sanity check on importing a node json should be cut out of it doesn’t match the expected format.

**Comment by psychedelicious** [comment]
This is an experimental feature meant to enable early exploration - the guardrails are off.

Everything in the node editor tab is "at your own risk", insofar as it's very easy to footgun yourself and crash things right now. For example, the connection validation logic is intentionally disabled. 

It will always be possible to provide invalid, app-crashing JSON *for this particular implementation of graph saving and loading*.

Generally, of course I agree 100% that you shouldn't be able to bork the app so thoroughly. A lot of care has been taken to prevent issues like this - in the areas of the app that are not marked as experimental. I hope that's clear as you use the app.

Given that...

- this is an experimental implementation of graph saving and loading
- it's not possible to provide full validation with this implementation, so it will always be able to crash the app fully
- it will be rewritten for release in a more sophisticated way with full validation
- there is a fix (to clear local storage)

... the solution to this issue is "don't do the thing that we know so break the app, and if you do, reset local storage".

I'm sorry you had the very unpleasant experience of a fully and fully borked ui.

**Comment by hipsterusername** [comment]
Closing as the "borked UI" issue is fixed in main and will be issued on next release
