### ISSUE TITLE
[bug]: Image gallery no longer file based 

### ISSUE THREAD

**Issue by mcbexx** [invoke-ai/InvokeAI#3895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0

### What happened?

I usually copy images back to the output folder if I want to grab a prompt from previously created images that have been moved to sub folders for better project organization. Also, cleaning up the output gallery with external apps is a lot easier than handling it via the UI, even with multi-select potentially on the horizon.

Now with 3.0, the image gallery no longer updates with images from the file folder when refreshing the UI page.
Images added to the output-folder are not added to the gallery on page refresh.
Also, images deleted outside of the UI are not removed from the gallery unless removed within the UI.

This feels like a big step back in usability, unless I am missing something?

**Comment by hipsterusername** [comment]
This isn’t a bug, and was an intentional decision made to support advanced functionality with a database. 

Understand the flexibility of direct file management, but given features we want to build to do more with images, metadata, graphs, etc. 

Recognize there are tradeoffs and that this may result in some changes in workflow. Encourage you to share more of your use cases so we can work to address those gaps with a DB based approach.

**Comment by mcbexx** [comment]
From this I gather there will be a way to import existing images (including metadata) into this database to extract old prompts?

**Comment by hipsterusername** [comment]
It looks like someone is sly working in that script, so yes!
