### ISSUE TITLE
[enhancement]: Download Board 

### ISSUE THREAD

**Issue by empessah** [invoke-ai/InvokeAI#3899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

empessah@gmail.com

### What should this feature add?

Feature request download boards It would be awesome to right-click a board and download all images or open the folder on the computer so you can grab them all at once. 

Second, for boards to be able to “pin” something to the top example working on a ControlNet project, I want the image I am always using up top to reference. Also, for images, I like to pin them to the top to download later. Maybe the pin is more of a star, and you can filter the star to the top. I don't know.

**Comment by StefanTobler** [comment]
@psychedelicious You can assign this to me. I see some logic for bulk download already exists as a "feature" however I don't see anywhere in the UI for this to be toggled. Any thing you can tell me about this?

**Comment by psychedelicious** [comment]
@StefanTobler Thanks!

See this issue for some more context https://github.com/invoke-ai/InvokeAI/issues/4832

The UI for this is disabled in `invokeai/frontend/web/src/features/system/store/configSlice.ts` in the `disabledFeatures` key. This slice of state is not persisted to browser storage, so when the bulk download feature is ready, you could remove it from this object.

The API endpoint is at the bottom of `invokeai/app/api/routers/images.py`. The actual bulk download should be initiated via this endpoint.

**Comment by StefanTobler** [comment]
@psychedelicious I would like your input on the implementation of this. 

My thought was to zip all the images selected or images from the board selected, and trigger a download in the browser.

I see two ways to do this:

1. Create a zip file on the backend and then return that in the response, triggering a download on the frontend.

~~2. Respond with all the image names, then create the zip on the frontend and just download there.~~ Thinking more about this, this is silly because then all the items are being individually downloaded to the frontend either way, unless that is the goal to download all of the images individually and not zipped.

As of right now I have gone down the path of 1, however the way the API has been implemented on the front end, it really does not like to parse the binary data from a zip file.

Any advice would be appreciated.

**Comment by StefanTobler** [comment]
Also should bulk download be a POST method? This certainly seems like it should be a GET request with the `image_names` and ` board_id` being URL parameters

**Comment by StefanTobler** [comment]
Also @maryhipp your advice would be helpful here to as I see you set up these endpoints so curious as to what you may have been thinking.

**Comment by StefanTobler** [comment]
Okay, I figured out how to get the files zipped up and they are being downloaded when returned by the browser. Next step is to figure out how to delete the zip file after the response has been sent. Ideally there is some fast API response where I can send the blob as a whole and bypass the "file path" stuff.

**Comment by psychedelicious** [comment]
Maybe a job for https://docs.python.org/3/library/tempfile.html

If you need to change the API endpoint we can discuss once you make the PR

**Comment by psychedelicious** [comment]
Also, have you tested this with, say, thousands of images? Is this fast enough to be a reasonable user experience?

**Comment by StefanTobler** [comment]
Good point, I will run some stress tests and also good call out for the tempfile, I figured out how to do it in-memory but writing to the disk with be key for folks with more files then memory.
