### ISSUE TITLE
[enhancement]: model config storage & data structure

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#4043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

There are two aspects of our model config storage with room for improvement: storage and data structure

## Storage

Currently we use YAML files to store model information like user-defined names and configs. 

**YAML Pros**
- Convenient for technically minded users and scripts to edit

**YAML Cons**
- You have to open a text editor
- Semantic whitespace is very confusing for non-technical users
- Its an additional entry point to configuring models besides the UI ("where should I update my models? in the UI or in this file?")

### Proposal: Use a database

We have an SQLite database that could store all of this. I'll add some implemenation thoughts further down.

**SQLite Pros**
- We can provide a strictly defined and structured interface for managing models -> harder to footgun (used by the app and scripts)
- Single entry-point for users (the UI)
- Single place for all model config data

**SQLite Cons**
- If you do bork it, potentially much harder to fix yourself
- Expect push-back from more technical users who want to edit the model configs directly

## Data Structure

The current data structure looks like this:
```yaml
# this is the model ID; {base model}/{model type}/{model name}
sdxl/main/stable-diffusion-xl-base-0.9a:
  path: models/sdxl/main/stable-diffusion-xl-base-0.9a
  description: ''
  vae: ''
  variant: normal
  format: diffusers
```

This is mostly fine - we need to store all of this information.

**Current Data Structure Pros**
- The model ID format gives you a good at-a-glance overview of the model

**Current Data Structure Cons**
- Model ID is not stable, it is derived from the name, which results in at least 2 user-facing issues:
  1. Changing the name of a model means past image metadata model entries are no longer useful
  2. When you change the name of a model in the UI, the currently selected model (in the parameters areas and in the model manager itself) is now invalid

## Proposal: Model ID is the hash of the model

The model ID should be a stable hash of the model, and `name` is now a property of the model (as opposed to being part of its ID).

## Implementation

We already have pydantic models for the model configs, and we use them internally (or we should if we don't already), so that's good.

Add a `models` table to the db:
  - `id`: hash of model, PK, calculated when the model is first added
  - `model_type`: eg `main`, `lora`, `vae`, etc
  - `model_format`: eg `diffusers`, `checkpoint`, etc
  - `data`: stringified JSON of the model config
  
Reading a model from the DB involves using `model_type` and `model_format` to determine which pydantic model to use to deserialize the model.

### Questions

Some specific things to consider
- How do we handle the user sticking their fingers in the pie?
- Do we need to calculate the model hash regularly? Maybe we have some `model checkup` logic to do this and validate the models haven't borked?
- As model formats evolve, we may need to do migrations on the data (probably we need a version column - probably need a version column in every table, maybe user techjedi on discord can assist)
- The model manager will need to use a generic storage interface, and we ship OSS with a SQLite implementation
- The configure scripts will need access to the DB, so said storage interface will need be available to them, or they will need their own interface. This may be tricky...
- The model manager has a lot of typing issues, and does some runtime dynamic class generation stuff. We may need to manually write the dynamically generated pydantic models and do a bit of tidying to allow a change like this.

#### Refs

Continuing a discussion started in #3902

### Alternatives

The bare minimum change we need is to make the model IDs stable. That could be done without moving to a database.

**Comment by lstein** [comment]
I very much like keeping structured data in databases. In addition to the advantages you point out, there’s also the safety of a transactional system that allows you to roll back failed updates - something that is tricky to do with files. So I’m in favor of this. At the very least, we should define an abstract base class for the model manager config storage backend.

With respect to IDs, I’m ambivalent about hashing the whole model. It seems inelegant and makes installation take that much longer. On the other hand, our recent experience with users downloading broken SDXL models pretty much mandates that we have to have a repository of known models and their hashes so that we can do integrity checking on downloaded models.

I don’t want users messing with the models yaml file, so another point in favor of this enhancement. We do however, need to be able to rebuild the database by scanning the models directory in the event that the db is deleted, corrupted or tampered with. The current model manager does this pretty well for models that are in `models` or the autoimport directories.

Another thing I’d like to change is to stop using the `models` directory structure to store the base model and model type. It is too tempting for users to try to install models there manually or move them around. I much prefer an install step in which the model is scanned once and its metadata saved to the config database/storage, and the user given the opportunity to examine the scan results and edit it if desired.

We should also take the opportunity to add additional (optional) metadata to models, including author, copyright info, creation date, source URL, license, and a thumbnail illustration of its output, among other fields.

**Comment by zopieux** [comment]
Wait, are you saying that the model hash used to identify models in metadata (such as the ones from Automatic parsed by Civitai) are just derived from the *name*? That's quite a terrible design, but I'd be in favor of not changing an established de-facto standard. Users want to be able to go back to old images and be able to restore settings from them.

Now, since Invoke uses a custom metadata format anyway it's probably a moot point. But if we write name and hash as metadata then I'd try to keep the historical/source model name (read-only in Invoke) and have the custom override kept locally in the DB.

+1 on not having to sha1sum the entire model just for the identifier stability. Integrity can be a nice feature but it's independen I think. I'd prefer if we could use a lightweight fingerprint instead, I'm sure plenty of libraries exist that do not read the entire file's content.

**Comment by psychedelicious** [comment]
@zopieux if you are referring to what I was saying about model IDs - no, I'm talking about InvokeAI specifically.

We are identifying the models like this, writing this to the image metadata (and graphs):
```
  "model": {
    "model_name": "sdxl-0.9",
    "base_model": "sdxl"
  },
  ```
  
`model_name` is user-changeable. I think A1111, comfy, and civitai use a properly stable unique identifier. Whether it is a hash of the file or something else I'm not sure. 

Also note those apps deal with checkpoint/safetensors models exclusively, which are a single files, while we are dealing with diffusers models, which are multiple files.

**Comment by zopieux** [comment]
ACK. Then yes by all means, let's try to use a stable identifier based on the model content itself. The fact we're dealing with bags-of-files is an implementation detail.

**Comment by lstein** [comment]
Setting aside the question of the storage backend, here are my thoughts about IDs.

1. Each model should have a stable hash that is derived from the model contents. @StAlKeR7779 and I think that a sparse hash mechanism such as that used by the [imohash package](https://github.com/kalafut/py-imohash) will create a reliably unique hash without incurring a bad performance penalty.
2. We might not want the stable hash to be the same as the key used to index the model. The key could be an internal unique incrementing number similar to a SQL primary key, that has no meaning outside the user's local database (regardless of whether it is a file or a db) and is not exposed to the API. On the one hand this is consistent with the relational database design of not storing metadata in keys. On the other hand, we'll have to enforce a constraint that the hash is unique to the database.
3. This is an opportunity for us to make the model entries much more rich in metadata. For example:
```
class ModelConfigBase(BaseModel):
   hash: str    # the hash/id
   name: str
   base_model: BaseModelType
   model_type: ModelType
   format: ModelFormat
   path: Path
   description: Optional[str]
   tags: Optional[Set[str]]
   source_url: Optional[str]      # URL for repo holding the model, if any
   thumbnail: Optional[str]      # Image URL for generating a thumbnail image (stalker's idea)
   active: bool = True                 # Whether the model should be shown in the UI
```
4. We can make it easier to search for models of interest:
```
mgr = ModelManager()
model_configs = mgr.search_by_tags({'scenery', 'realistic'}, model_type='main', base_model='sd-1')
model_configs = mgr.search_by_name('yiffy*', model_type='main', base_model='sd-1')
model_configs = mgr.search_by_path('/usr/etc/models/')   # e.g. can constrain with model_type & base_model
model_configs = mgr.search_by_type(model_type='main', base_model='sd-1')
# (etc - many more variants - could be combined into one mega-method possibly)
for entry in model_configs:
    model = mgr.get_model(entry.hash)

# unlike others, this only returns one value, the model context
model = mgr.get_model('09809adfa09')
```
5. Other API calls:
```
exists = mgr.model_exists(hash)
model_config = mgr.model_config(hash)
model_configs = mgr.list_models(hashes)

# adding a model
# installation happens as a background thread and the state of installation can be retrieved from 
# the load_info obect. This was Stalker's suggestion.
load_info = mgr.add_model(model_name, base_model, model_type, model_config)
if load_info.state == LoadState.Initializing:
   pass
if load_info.state == LoadState.Downloading:
   pass
if load_info.state == LoadState.Processing:
   pass
if load_info.state == LoadState.Validating:
   pass
if load_info.state == LoadState.Error:
    raise Exception(load_info.error)
if load_info.state == LoadState.Installed
    model_hash = load_info.config.hash

# deleting a model
try:
    mgr.del_model(hash)
except ModelNotFoundException:
    pass
    
# converting a model
mgr.convert_model(hash)

# import an arbitrary URL, path or repo_id
load_info = mgr.import_model('stabilityai/stable-diffusion-xl-base-1.0')
```

**Comment by Millu** [comment]
Close by #5694
