### ISSUE TITLE
[bug]: Node Graph: Seed inputs going rogue

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#4317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.2

### What happened?

Based on the node graph metadata, any node getting "seed" integer as input seems to generate a random seed no matter what input as been fed. Further more, reversing the process of copying the seeds from the metadata into the graph nodes doesn't result in the same images. Something up with the seed input and/or the metadata being saved to the images.

**Comment by Millu** [comment]
What version of the node editor are you using? Tracking main or the one included with 3.0.2post1?

**Comment by Neosettler** [comment]
That would be 3.0.2

**Comment by psychedelicious** [comment]
This is actually a misunderstanding of what the Graph metadata is showing you - it shows the graph that was sent to the server and executed - *not* the graph with all individual node results populated.

The wonky part is that the `seed` parameter of the `noise` node gives itself a default value if one isn't provided directly - but whatever value it gets from a connection overwrites the default. So that's why you see the same value in every graph - its just choosing a seed that doesn't actually get used.

We will be resolving the user-facing issue by using a workflow + execution graph as the metadata, not the source graph.
