### ISSUE TITLE
[enhancement]: Click and drag the end of the connector to remove the connector

### ISSUE THREAD

**Issue by suonnon** [invoke-ai/InvokeAI#4338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I have some suggestions for Node Editor and I hope they could make the Node Editor more easier to use 🙏:
- Del/Delete button on keyboard also works for removing node(s)/connector(s)
- Multiple selections works when intersects with selection marquee instead (like selecting objects in Photoshop or Illustrator or Blender nodes)
- Generated Image node: a node for viewing the generated image, resizable node, click image to fullscreen view
- Click and drag the end of the connector to remove the connector (like Blender did for node editor)
- Duplicate selected node(s), copy/paste selected node(s)
- Preview image on the node (e.g: controlnet,...) should be smaller as a thumbnail instead of actual size of the input photo.
- Search/Add node box: moving it to the bottom center or top center would be better I guess.

**Comment by psychedelicious** [comment]
Most of these are already implemented in the `main` branch or active PR and will be in the release of the node editor:
[x] Del/Delete button on keyboard also works for removing node(s)/connector(s)
[x] Multiple selections works when intersects with selection marquee instead (like selecting objects in Photoshop or Illustrator or Blender nodes)
[x] Generated Image node: a node for viewing the generated image, resizable node, click image to fullscreen view
[ ] Click and drag the end of the connector to remove the connector (like Blender did for node editor)
[x] Duplicate selected node(s), copy/paste selected node(s)
[x] Preview image on the node (e.g: controlnet,...) should be smaller as a thumbnail instead of actual size of the input photo.
[x] Search/Add node box: moving it to the bottom center or top center would be better I guess.

We use Github to manage and prioritize feature development, so each request should be for one specific thing. Please make individual, focused requests for each feature you want to see.

**Comment by psychedelicious** [comment]
We are super hyped for the official nodes release too :)

I'll retitle this request to be for the remaining feature.
