### ISSUE TITLE
'editOptsForm' object has no attribute 'vram'

### ISSUE THREAD

**Issue by justostoll** [invoke-ai/InvokeAI#4451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What version did you experience this issue on?

3.1.0

### What happened?

A problem was encountered during the configuration and download steps: 'editOptsForm' object has no attribute 'vram'
It also happens after filling in the first page of the form that is shown with the command: invokeai-configure --root . 
Giving the following error: AttributeError: 'editOptsForm' object has no attribute 'vram'. Did you mean: 'ram'?

### Contact Details

success_bunches.0e@icloud.com

**Comment by markrmiller** [comment]
Same. Can't do a fresh install.

**Comment by DavidCWGA** [comment]
Same here. I hacked a fix by commenting out line 594 of invokeai_configure.py - in other words removing "vram" from "attr", but I doubt this is the correct thing to do.

**Comment by lstein** [comment]
Known bug. Is fixed in `main` and will be released in `3.1.2`. You can grab the fixed .py file here: https://raw.githubusercontent.com/invoke-ai/InvokeAI/main/invokeai/backend/install/invokeai_configure.py

If you are using a `.venv`, the file to replace is `.venv/lib/python3.11/site-packages/invokeai/backend/install/invokeai_configure.py` (warning: not `frontend` - this is a different file)

**Comment by Millu** [comment]
Fixed in 3.1.1
