### ISSUE TITLE
Generation Values in Image Metadata from Workflows

### ISSUE THREAD

**Issue by ebr** [invoke-ai/InvokeAI#4495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Currently when images are produced by the linear UI, their metadata includes values used at generation time, such as the value of random seed.

When the image is produced by the workflow, only the workflow is included, but not the values of any nodes computed at graph execution time using e.g. the Random Integer or Float nodes. So for images generated via the workflow editor, we have no way of recalling the random seed, CFG scale, steps, etc, which were used at Denoise Latents stage. This makes it impossible to reproduce an image created by the workflow even when workflow itself is known.

is there a way to include the output values of "random" or "range" nodes at graph execution time for each individual image?

**Comment by psychedelicious** [comment]
First let's define "workflow" and "image metadata" of an image/output:
- "workflow": the graph, plus some workflow metadata, that was run to generate the output(s)
- "image metadata": the relevant values used during the creation of a given image, which may be present in the workflow OR may be the results of execution of nodes in the workflow

Include image metadata values in the workflow itself would require qualitatively changing the workflow. For example, the random int node cannot be trivially replaced with the number that it generated. The workflows are not equivalent to image metadata

---

The need, then, is a generalized strategy to get arbitrary metadata into the image metadata (not the workflow graph). 

Currently, the linear UI uses a strictly typed metadata accumulator node to do this. It has explicit inputs and outputs. 

An improvement would be a more flexible metadata accumulator which accepts an array of key-value pairs which represent the data that should be in the image metadata. 

We cannot just use field names as the keys, because we can have multiple fields with the same name. Consider any denoising node - it needs two "prompt" fields. Thus, the user needs to be able to define the names for each value.

There was a discord discussion around this and it landed on this:
- A `MetadataItemInvocation` node that has a `key: str` field and `value: Any` input, with a single `MetadataItem` output field
- A `MetadataAccumulator` node that accepts a collection of `MetadataItem`s, builds a dict of them and outputs a `MetadataDict`
- You'd either connect desired node outputs into `MetadataItemInvocation` nodes, or populate values directly in these nodes, then route all of them into a `Collect` node, and finally output the collection into the `MetadataAccumulator` node
- Any image-outputting node has a `metadata` field that takes the metadata dict and includes it when writing the image

This needs some internal changes - namely, support for `Any` as an input field type. We'd need to be very careful about how this is used, because `Any` is a potentially dangerous thing.

With this setup, users could add arbitrary metadata to an image. We'd likely migrate the existing linear UI graphs to use this also.
