### ISSUE TITLE
[bug]: multiple delete

### ISSUE THREAD

**Issue by VeyDlin** [invoke-ai/InvokeAI#4885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

11

### What version did you experience this issue on?

3.3.0

### What happened?

If you select several images and press the delete key on the keyboard then this will work only for one image

**Comment by psychedelicious** [comment]
I'm not sure if this is really a bug.

The delete handler is in `invokeai/frontend/web/src/features/gallery/components/CurrentImage/CurrentImageButtons.tsx`, which isn't available when the those buttons are not mounted.

Let's first explore what the behaviour should be for combinations of these states:
- Gallery open or closed
- single or multiple images selected
- current image buttons visible or hidden (e.g. you are on canvas or workflow editor)

What is the desired behaviour in each combination?

**Comment by psychedelicious** [comment]
Sorry you lost your selection.

There's some miscommunication. It's not a good UX, I agree, but also it's not a "bug" - it's doing exactly what it's supposed to do - delete the current image. But when you have many images selected, this is not the expected behaviour.

It's not clear what the expected behaviour is, hence my probing question. Do you have any ideas for my question?

**Comment by ufuksarp** [comment]
I know this is not the right place to ask, but do I have to delete images from my folder aswell after deleting them from the gallery? Is there a way to delete both at once?
