### ISSUE TITLE
[bug]: Return key triggers the cancel button in "Cancel and Clear All Items" prompt

### ISSUE THREAD

**Issue by gaspesla** [invoke-ai/InvokeAI#4927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

cuda

### VRAM

32GB

### What version did you experience this issue on?

3.0.0

### What happened?

When I click on the **Cancel and Clear All Items** button, there's a dialog box prompt with **Clear** and **Cancel** buttons. If I press the return key on my keyboard,  this appears to trigger **Cancel** rather then **Clear**.

### Additional context

Safari 17

### Contact Details

plugtwo@gmail.com

**Comment by Millu** [comment]
Could you update to the latest version 3.3.0post3 and see if the behavior persists?

**Comment by psychedelicious** [comment]
This is intentional.

The ARIA accessibility guidelines indicate that when context changes - like in an alert dialog - the focus should be on the least destructive option. In this case, that is the cancel button.

You can press `tab` and then `enter` to get to the clear button.

**Comment by gaspesla** [comment]
With respect to guidelines, I have been using computers for 30 years and I've never seen the return key press a Cancel button. It's just not a thing.

**Comment by psychedelicious** [comment]
It definitely is a thing, but perhaps the particular alert dialogs with which you've interacted have not been built according to the [Web Accessibility Initiative's guidelines for accessibility.
](https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog/examples/alertdialog/#accessibilityfeatures)

These guidelines are intended to support individuals who use assistive technologies. A common example would be a screen reader, for those with vision problems, but there are many others.

The "focus on the least destructive action" behaviour is [explicitly built into Invoke's chosen UI component library.](https://chakra-ui.com/docs/components/alert-dialog#accessibility). It was chosen specifically because it handles the rather difficult task of making the UI accessible. There are a *ton* of other accessibility features, this is just one of many.

While I understand that this behaviour seems unusual to you, we are going to follow the accessibility guidelines when possible.

If you have some other idea for improving this particular interaction, of course that's something we can explore. It's only the accessibility-guideline interaction that are not up for debate.
