### ISSUE TITLE
[bug]: Generating with Hi-Res fix generates different image than without Hi-Res fix

### ISSUE THREAD

**Issue by schuster-rainer** [invoke-ai/InvokeAI#5169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

42GB (M1 MAX shared RAM)

### What version did you experience this issue on?

3.4.0post2 (the lastest available via the commandline)

### What happened?

I rendered an image in 512x768. Then I wanted to highres fix it.

1. Used the same seed.
2. turned on highres-fix 
3. Ran the same prompt with the same seed
4. Set the denoising to 0.3

two different images appeard. It's not working as in auto1111 where you can highres fix an image.
I would expected to get the same image but with some highres-fix aplied. Similiar  as in when I do an img2img upscale with controlnet tile mode

### Screenshots

512x768
![image](https://github.com/invoke-ai/InvokeAI/assets/67356/fe00d80e-8b9b-4fe1-b121-62133c8dce7d)

same prompt and seed with highres-fix at 0.3
![image](https://github.com/invoke-ai/InvokeAI/assets/67356/d3abd3f7-a705-4abc-944f-79a2ed239777)

**Comment by Millu** [comment]
This is interesting - I'm not able to replicate this at 512x512 but the issue appears at 512x768

cc: @marict any chance you're able to look into this?

**Comment by psychedelicious** [comment]
I did some brief testing.

This is happening because the logic to choose the initial image size doesn't want to choose 512x768. It is trying to choose the closest initial size, in area, to 512x512. This is done with the assumption that 512x512=262144 pixels is the ideal area for the model, but 512x768 is often a fine size for sd 1.5 models.

When I set my size to 1024x1536 (twice 512x768), it chooses 416x624 as the initial dimensions.

Interestingly, 416x632 is closer to 512x512 than 416x624, so that calculation may be a bit off.

We are working on a refactor of model management, which will allow models to self-report their optimal dimensions. When that is ready, we can make the hires fix logic more sophisticated.

Maybe we can find ways to improve it before that time too.

**Comment by marict** [comment]
From what I understand, this behavior is expected when using the high-resolution fix in tools like InvokeAI and similar ones that generate images at a lower resolution and then upscale them.

In the "automatic1111" tool, you specify a resolution that's higher than your current generation settings, like this:

1024x1024 (generation resolution) -> high res fix -> 2048x2048 (upscaled)
However, in tools like InvokeAI or DrawThings, it works like this:

512x512 (initial hidden resolution, chosen automatically) -> high res fix -> 1024x1024 (generation resolution)
The key difference is that the upscaled denoising step introduces less variability in the image compared to the initial generation step. So, in "automatic1111," you still get a different image, but the differences are mainly in the fine details rather than the overall structure of the image.

I hope this clarifies things for you.

**Comment by marict** [comment]
> This is interesting - I'm not able to replicate this at 512x512 but the issue appears at 512x768
> 
> cc: @marict any chance you're able to look into this?

The reason you weren't replicating this at 512x512 is because the resoultion being chosen is whatever is "closest" to 512x512, so in that case it wasn't upscaling at all, just running another couple denois steps.

This is one of the cons (there are pros) to having the initial generation resolution be hidden, since it can be unclear what the initial resolution is and what behavior that implies.
