### ISSUE TITLE
[bug]: Width and Height change on switching 1.5 models

### ISSUE THREAD

**Issue by TheCulprit** [invoke-ai/InvokeAI#5452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.6.0rc5

### What happened?

When using a 1.5 model, if the width/height boxes are set to anything other than 512x512 then on switching to another 1.5 model the sizes will change. This only seems to apply the t2i and i2i tabs. The UC is unaffected.
Sizes change when switching from 1.5 to XL models seems to work as intended however switching back results in the same errors in the sizing.

When switching from a 1.5 model at 512x768 to another 1.5 model the size ends up at 416x624
When switching from a 1.5 model at 512x768 to an XL model the size ends up at 840x1256.
Switching back to a 1.5 model and the size ends up at 416x624 again.

Same behaviour in Chrome and Firefox.

### Contact Details

Stretch (villainstretch) on Discord

**Comment by hipsterusername** [comment]
@psychedelicious - I think the issue here that violates User expectations is that we're switching W/H on 'same model architecture' and "optimizing" something that's technically valid in user's mind. Rather than try to do weird things w/ optimization calc, I'd wager just "only resetting sizes if switching architectures" would solve the problems. 

Alternatively, could revert our last change, but I think the above is the "ideal".
