### ISSUE TITLE
Remove magenta hue from img2img outputs

### ISSUE THREAD

**Issue by cvar66** [invoke-ai/InvokeAI#552]
Using img2img and looping the image back through it causes an increase in magenta hues and saturation of the output image. I think they used this fix https://github.com/Pyr-000/YetAnotherStableDiffusion/commit/b8751862de557edd0cad2d9f7e4b4e46c3f3042c in the Automatic1111 fork to fix this and it works pretty good so far from my limited testing.  Would be a nice to add this or something similar.

**Comment by hipsterusername** [comment]
Seconded - I've noticed this often in feeding forward images.

**Comment by veprogames** [comment]
This is probably the same issue that occured in https://github.com/lstein/stable-diffusion/pull/156#issuecomment-1229511957 around 2 weeks ago. How fast this magenta effect occurs seems to depend on strength between individual frames. With a higher strength, it takes longer (since less of the previous image is kept).

**Comment by psychedelicious** [comment]
This was very close to resolved in #613 (the issue of color drift is not 100% solved in any implementation, but things are working quite well). Closing as resolved.
