### ISSUE TITLE
[bug]: Can't Launch or Fix Installation (MetadataIncompleteBuffer and CLIP-ViT-bigG-14-laion2B-39B-b160k missing)

### ISSUE THREAD

**Issue by Astra060** [invoke-ai/InvokeAI#5741]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

2060m

### GPU VRAM

6GB

### Version number

3.7.0

### Browser

Chrome - Latest

### What happened

After Installation 
A. I decided to check installation with option number 6 from invoke.bat, and then got this error:
```
[2024-02-18 11:38:41,901]::[InvokeAI]::INFO --> Downloading core tokenizers and text encoders
[2024-02-18 11:39:04,901]::[InvokeAI]::ERROR --> Error while deserializing header: MetadataIncompleteBuffer
```

B. Tried Launching the WebUI, got this error:
```
CLIP-ViT-bigG-14-laion2B-39B-b160k is missing
```
I checked HG, each model was 10GB! No way this is the right model

C. I rechecked downloaded models with 4 in invoke.bat, everything was fine.

I did all this and have no idea what file I'm missing. The errors are useless, don't tell me where the error is originating. Anyway to actually understand which file is causing this and where this problem was? Not just MetadataIncompleteBuffer

### What you expected to happen

Application should have launched, or fixed itself, non happened

**Comment by lstein** [comment]
I've never seen this error message before, but it would be coming from the HuggingFace model download API. The thoughts that spring to mind are either (1) the HuggingFace repo was having problems at the time you tried to install; or (2) your HuggingFace models cache has gotten corrupted somehow.

If the problem was (1), then the issue should have cleared up spontaneously. To address (2), please locate a directory named `.cache\huggingface`, which should be located in your User directory. Either remove or rename it, and try running option 6 again. If this still isn't working, you could also try removing the directory `invokeai\models\core` before doing option 6.
