### ISSUE TITLE
[enhancement]: Differential Diffusion: Giving Each Pixel Its Strength

### ISSUE THREAD

**Issue by exx8** [invoke-ai/InvokeAI#6038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Hello,
I would like to suggest integrating my paper: Differential Diffusion: Giving Each Pixel Its Strength.
The paper allows a user to edit a picture by a change map that describes how much each region should change.
The editing process is typically guided by textual instructions, although it can also be applied without guidance.
We support both continuous and discrete editing.
Our framework is training and fine tuning free! And has negligible penalty of the inference time.
Our implementation is diffusers-based.

The paper can be thought of as a generalization to some of the existing techniques.
A black map is just regular txt2img ("0"),
A map of one color (which isn't black) can be thought as img2img,
A map of two colors which one color is white can be thought as inpaint.
And the rest? It's completely new!
In the paper, we suggest some further applications such as soft inpainting and strength visualization.

Site:
https://differential-diffusion.github.io/
Paper:
https://differential-diffusion.github.io/paper.pdf
Repo:
https://github.com/exx8/differential-diffusion

### Additional Content

We attach some examples here:
https://differential-diffusion.github.io/

Thanks

**Comment by hipsterusername** [comment]
We have something similar to this - but there seem to be some areas that are a bit different.

@dunkeroni - what are your thoughts?

**Comment by dunkeroni** [comment]
> We have something similar to this - but there seem to be some areas that are a bit different.
> 
> @dunkeroni - what are your thoughts?

Same math, different name.

This I believe was the original paper on the topic, it stayed fairly quiet for a long time. I started experimenting with what I called Gradient Denoise, and around the same time A1111 Forge introduced Soft Inpainting, from which some folks in the community pointed back to the Differential Diffusion paper.

For canvas, we are currently using it for edge blending on inpaint operations.

If you want to use the other implementations (img2img where the full time step range is processed for more accurate sampler momentum, depth map background replacement and blending, etc.) then you can use the Create Gradient Mask node and leave the blur radius at 0, which will skip any adjustments and flag the mask for Gradient processing.

@hipsterusername if we want to honor the initial discovery, we can update our naming conventions to match, but it was an independent invention. Though to be perfectly frank, a differential across a surface or otherwise higher order dimensional space is correctly called a gradient.

**Comment by dunkeroni** [comment]
Additional note:
Once we have support for multiple layers in the canvas ( #4466 ), we can also include multiple mask layers at individual strengths that will merge together and act at different times in the denoise process. That is already supported in our implementation, we just don't have the frontend for it yet.

**Comment by hipsterusername** [comment]
@dunkeroni - Ah ha. knew it was similar but didn’t realize it was almost a 1:1. I think given your independent development of it, we will leave as is and close this as completed.
