### ISSUE TITLE
Only load modules when needed and unload when finished with them

### ISSUE THREAD

**Issue by Vargol** [invoke-ai/InvokeAI#610]
**Is your feature request related to a problem? Please describe.**
To keep GPU memery requirements low we currently only load the modules them if
we are going to use them,
As many of us are on Unified Memory Architectures where all Memory is GPU memory
I wondered if this could be applied to SD in general e.g. why are we loading three types
if samplers if we are only using one.
Also, can we unload modules we are finished with e.g. do we need the argument parsing
modules once we've parsed the arguments. The internet seems a little divided if modules unloading works
but its suggested the 

del os 
sys.modules['os']
would unload the os modules for example.  

**Describe the solution you'd like**
Minimize SD's memory usage as far as possible, so UMA GPU's have a s much memory as possible.

**Describe alternatives you've considered**
At least don't load modules in unnecessarily

**Additional context**
No I'm not sure if this would really make much of a difference for most modules and hope someone that knows python better could respond to this.

**Comment by tildebyte** [comment]
For models, this makes sense - less so for *Python modules*. Python is very text-based (interpreted) and quite fine-grained, so while you do of course get "dependencies of dependecies", as long as you avoid truly noob stuff like `import *` and stick to only importing what you really need - you are literally able to import a single text function from a source module composed of dozens of functions.

All of that to say that unloading Python *modules* is only worth it if you're talking about something pretty big, otherwise you might be looking at an import whose size is only tens of lines of text  - at that point it's not really worth the bother. The caveat is if you've got a module like 'numpy' where there are actual compiled binary libs involved - that *might* be worth looking into, but see below - I don't beleive that we could successfully unload *part* of e.g. 'numpy'.

I'm probably out of my lane here, but if I understand the intent and context of the question- Python is entirely unlike a complied language like c, where even dynamically linking against one function in a dll pulls that entire dll into memory (IIUC -I'm no c expert :D)

**Comment by lstein** [comment]
Someone correct me if I'm wrong, but I don't think you'll get the memory back if you unload a python module. It will remain in use by the process and can be reused by a different module, but won't free up memory for any other processes.

**Comment by tildebyte** [comment]
Actually, that **sounds** correct; I've never actually looked into it.

**Comment by Vargol** [comment]
All this is coming from as a couple potential issue with dream.p.

The first is that  the production and dev branches have started throwing memory errors (but dream.py doesn't stop and I do get an images at the end) at 1024x1024 for me, the 1.14.x optimisation branch wasn't doing this. However I've also upgraded macOS between tests so am not convinced thats a SD issue yet I need to go back to my old fork and do some testing.

The order issue s one  that has been around a while, If I start dream.py , while at the dream prompt the python process uses ~ 4.8 GB, if I then run a image generation when It gets back to the dream prompt the python process is then using ~ 10.7 Gb.
If a rerun the same prompt if is then significantly slower

e.g from a test run, all prompts were

`"banana sushi" -s1 -C7.5 -n1 -W1024 -H1024
`

```
Before 4.88Gb
Render at 56 s/it
After 10.76Gb
Render 73.41s/it
After 10.88Gb
Render 79.41s/it
After 10.92GB
Render 85.41s/it
After 10.90GB

```
Now if it was a memory leak I'd expect the memory usage to keep on going up, but somewhere a lump of 5Gb of memory
is created that doesn't go away and adversely affects my rendering speeds from the second render onwards. I was hoping it was something that could be unloaded.

There's a similar but smaller affect when doing multiple iters  55s/it -> 62s/it but the third iter is usually at the  same speed as the second where as multiple prompts seems to get slower.
 
I can raise this as a separate issue if you like, but it'll be much later in the day.

**Comment by tildebyte** [comment]
These are my educated guesses

>  If I start dream.py , while at the dream prompt the python process uses ~ 4.8 GB

Unavoidable Python overhead - you get this with anything you run, even compiled languages (e.g. glibc), although obviously much less for them

> but somewhere a lump of 5Gb of memoryis created that doesn't go away

This is almost exactly what one would expect for the **models** (not Python modules) after they load

**Comment by Vargol** [comment]
So what models are loaded during processing and why is the second run slower it it does not have to load the model again ?

**Comment by tildebyte** [comment]
> So are models are loaded during processing

Primarily (size-wise) the Stable Diffusion model itself (it's just over 4GB), plus a couple of other smaller ones. Unloading those isn't an option.

> why would the second run slower if it does not have to load the model again

That I don't know - I suspect it's something to do with macOS or the M1 architecture, but I gave up on Apple computers 4-5 years ago

**Comment by Vargol** [comment]
So those are loaded before the dream prompt ?

**Comment by tildebyte** [comment]
I'm not sure. Like I said, educated guesses.

**Comment by jn-jairo** [comment]
Yes, it is possible to use less VRAM.

I am using a optimized version based on the original Stable Diffusion and it requires only a 2GB GPU (my GPU is 2GB, that is why I expended so much time to make it fits in 2GB) with that I can make images up to 576x576.

The secret is to split the model and offload then to cpu when it is not being used and do the attention calculation in parts.

Of course, it is a bit slower due to the time to transfer the memory, but it is a great option for those who have few VRAM, because it is faster than running it on the CPU.

The version I use is basically a fork of the [basujindal/stable-diffusion](https://github.com/basujindal/stable-diffusion) with a new command line interface and some small fixes.

If you would like, that can be added to this repository as a optional feature.

P.S. At this time the readme in [basujindal/stable-diffusion](https://github.com/basujindal/stable-diffusion) is not updated with the current memory requirements (2GB GPU).

**Comment by tildebyte** [comment]
> If you would like, that can be added to this repository as a optional feature

We're always interested in PRs

**Comment by jn-jairo** [comment]
> > If you would like, that can be added to this repository as a optional feature
> 
> We're always interested in PRs

Great, so I will work on that PR as a optional feature.
