### ISSUE TITLE
[bug]: Diffusers conversion error

### ISSUE THREAD

**Issue by izumikon123** [invoke-ai/InvokeAI#6172]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

2080Ti

### GPU VRAM

12

### Version number

4.0.4

### Browser

Edge

### What happened

When converting ckpt to diffusers got error: 
No such file or directory: 'E:\\Data\\AI\\INVOKE3\\configs\\stable-diffusion\\stable-diffusion\\sd_xl_base.yaml'

error is that "\stable-diffusion\stable-diffusion\" should just be "\stable-diffusion\"

### What you expected to happen

ckpt to be converted to diffusers format

### How to reproduce the problem

attempt to convert a ckpt model

**Comment by psychedelicious** [comment]
Did you get this when clicking the Convert button in the model manager?

**Comment by izumikon123** [comment]
yes, this is the only way I know how to convert models in the new gui

**Comment by psychedelicious** [comment]
Thanks. We can fix this bug, but I'm curious if you actually want to convert the model permanently or just use the model. If you want to use the model, the model manager handles on-the-fly conversion for you.

**Comment by izumikon123** [comment]
I want to convert the model permanently - I download models as ckpt, and convert them then delete the original model to save disk space, thanks for addressing it!

**Comment by psychobyte-nl** [comment]
I think I had the same issue right after converting Invoke. In my case the issue persisted due to the **legacy_conf_dir** parameter with value **configs\stable-diffusion** remaining in my **invokeai.yaml**. You can correct the path by removing the bonus **\stable-diffusion** from each configuration path, but removing the parameter from **invokeai.yaml** all together, assuming you did not use any custom path for configurations, solves that problem permanently.

**Comment by psychedelicious** [comment]
Thank you @psychobyte-nl, yes, that could definitely cause this problem. @izumikon123 please let us know if that solves the issue for you. It's possible there is way this could happen.

**Comment by izumikon123** [comment]
This works, thank you!
