### ISSUE TITLE
[bug]: Import models from huggingface or civitai fail error code 5 (Google Collab)

### ISSUE THREAD

**Issue by Lucretius0000** [invoke-ai/InvokeAI#6177]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

None (CPU)

### GPU model

Google Collab Nvidia T4

### GPU VRAM

16 GB 

### Version number

4.0.4

### Browser

Firefox Latest version

### What happened

Hello it happens randomly when i import any file sometimes it refuses to copy and gives me this error inout output in the install queue tab, neither resetting the collab works, it does work if you are lucky

### What you expected to happen

i cant replicate it , it does happen casually

**Comment by psychedelicious** [comment]
Please provide the terminal output showing the full error message.

Without seeing the full error, it sounds like a network error, which means the problem is between the computer on which invoke is running and the remote server hosting the model file. We can't do anything about that.

Also, we don't support Google Colab. In fact my understanding is that using Invoke on Colab is against the Colab terms of service.
