### ISSUE TITLE
[bug]: Manually backing up and restoring models during an upgrade

### ISSUE THREAD

**Issue by SoftologyPro** [invoke-ai/InvokeAI#6265]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

N/A

### GPU VRAM

N/A

### Version number

4.2.0

### Browser

N/A

### Python dependencies

N/A

### What happened

I want to have the ability to not have to download models again if I do a fresh install.  So, I trioed...
1. Make a copy of the models folder.
2. Delete InvokeAI and install the latest clean.
3. Copy models directory back.
4. Start InvokeAI.
Models are not selectable?
Is there an additional file(s) that needs to be backed up to retain the models?

### What you expected to happen

I expected the models to be usable.

### How to reproduce the problem

See "What happened"

### Additional context

N/A

**Comment by psychedelicious** [comment]
Invoke uses a database to store all user data. This includes images data, workflows and model entries. See: https://invoke-ai.github.io/InvokeAI/features/DATABASE/

The database is stored in the installation directory, so by deleting that, you are deleting the model entries. It's inadvisable to _partially_ delete certain the install dir, because that would leave the database out of sync with the files on disk.

However, for models, there is an easy fix to reinstall the models. You can follow the same process you listed, and then follow this FAQ at the end to restore the models: https://invoke-ai.github.io/InvokeAI/help/FAQ/#missing-models-after-updating-to-v4

**Comment by SoftologyPro** [comment]
OK, thanks.
