### ISSUE TITLE
[bug]: Use All hotkey (A) doesn't work on editing mode

### ISSUE THREAD

**Issue by ufuksarp** [invoke-ai/InvokeAI#6398]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Version number

4.2.1

### Browser

Edge latest

### What happened

Pressing **A** doesn't trigger **Use All** on editing mode, it should.

**Comment by psychedelicious** [comment]
The hotkeys are enabled when an image is visible in the viewer - same behaviour as on canvas, where the metadata recall hotkeys aren't enabled at all. I'm not convinced this should be changed

**Comment by ufuksarp** [comment]
Why is there a limit? These recall keys are not used for other functions in canvas or control layers. Why does the user need to go into viewing mode to recall the settings?

When a user wants to check the control layers settings to click "Control Layers" button, they are automatically transferred into the editing mode, in which they have to either switch back with Z key or have to use the right-click menu which is unnecessarily more work.

If auto-switch (#6400) is made configurable, then this is less of an issue. Even still, why the limit?

**Comment by psychedelicious** [comment]
The hotkeys are implemented in the image viewer component - that's the core reason why it only works when that component is visible.

It's possibly unintuitive to enable recall hotkeys with multiple selections, when the viewer isn't open to show you the last-selected image. We can work around that though.

How does this sound? 
- Recall hotkeys are enabled when the gallery is visible and a single image is selected.
- Recall hotkeys are disabled when multiple images are selected and the viewer is closed, because it's not clear what specific image you'll be recalling from.

**Comment by ufuksarp** [comment]
> The hotkeys are implemented in the image viewer component - that's the core reason why it only works when that component is visible.

I was suspecting that was the case.

> It's possibly unintuitive to enable recall hotkeys with multiple selections, when the viewer isn't open to show you the last-selected image. We can work around that though.
> 
> How does this sound?
> 
> * Recall hotkeys are enabled when the gallery is visible and a single image is selected.
> * Recall hotkeys are disabled when multiple images are selected and the viewer is closed, because it's not clear what specific image you'll be recalling from.

That all sounds logical.
