### ISSUE TITLE
IMG2IMG picture quality (compression,artifacts)

### ISSUE THREAD

**Issue by smoke2007** [invoke-ai/InvokeAI#652]
**Describe the bug**
I've been doing a lot of img2img and i've been noticing that often the quality of the resulting image contains a lot of what seems JPG compression, compared to how pristine the input image was. Ofcourse only noticeable when using masking, as img2img on the complete image would result in something completely new and not comparable.

**To Reproduce**
use an original image and a masked image, create an img2img and compare the quality of the non-masked area.

**Expected behavior**
Less compression and artifacts of the non masked area of the image

**Comment by lstein** [comment]
That's an interesting observation. Are you using the output of img2img as the input to another round repeatedly? I suppose that what could be happening is that the image is being compressed and uncompressed multiple times. PNG actually does use lossy compression, so this is a real concern.
If you think this is what we might be seeing, then we can change the compression level when we write out the generated PNG files to something less aggressive. I'm hoping to get back to working on inpainting tomorrow (Sunday) and I can tweak compression then. Just tell me how to best trigger the problem.

**Comment by smoke2007** [comment]
![generated](https://user-images.githubusercontent.com/17826183/190878147-72262a44-4d27-4ee0-ae83-a6eb25440f0b.png)
![test-o](https://user-images.githubusercontent.com/17826183/190878154-88664289-5217-4ef4-9008-271e3ab4c68a.jpg)
![test-m](https://user-images.githubusercontent.com/17826183/190878159-51c7668b-a4e7-4d6b-9fba-55fef13f457d.png)

i'm actually not sure what i'm seeing, testing it with a really close up face now, it's like it slightly does change the entire photo and not just the part that was masked. If I overlay them in photoshop , the hairs have slightly shifted , the lip creases, the teeth. and I only masked her earring and replaced it. So it's either compression or SD is doing its best to recreate the original but only gets it 99%

**Comment by smoke2007** [comment]
and here look with face that isn't as close up , only masked the balloon and changed it , the girls eyes get deformed

![test2-m](https://user-images.githubusercontent.com/17826183/190878327-0190a94d-3fd0-4b01-b5cb-89e2c3b19a31.png)
![test2-o](https://user-images.githubusercontent.com/17826183/190878328-68be853d-22ae-4919-bbd4-fae8bbeca88b.png)
![000404 1325171461](https://user-images.githubusercontent.com/17826183/190878337-b16fee4d-65c4-410e-a213-c2e4e85034b8.png)

**Comment by smoke2007** [comment]
here's a girl not in close up , masked the balloon and switched it out. notice the resulting image where the face of the girl gets deformed anyway.

![test2-m](https://user-images.githubusercontent.com/17826183/190878390-531e148d-4f67-4827-a3ed-aca779b2e43a.png)
![test2-o](https://user-images.githubusercontent.com/17826183/190878391-b1e5ad36-402a-4e1f-b702-34648097f7da.png)
![000405 3623935117](https://user-images.githubusercontent.com/17826183/190878392-1815d14d-2f0b-46ec-9a0d-bda4cc32968b.png)

**Comment by netsvetaev** [comment]
For the first closeup one, it looks to me like a lack of interpolation on the original image. See the eyelashes made of hard pixels, and the edges of the teeth. The other differences are only noise.
The second one is affected clearly outside the region.

**Comment by CodeExplode** [comment]
SD downscales all its input images to 64x64 (whether they're pure noise, or a weighted combination of an image + noise), does its magic, and then upscales back up to 512x512 at the other end (somehow). It seems likely the way that the masking works is that it's preventing changes to the 64x64 version, but it's still passing through SD's downscale and upscale process. If so it could in theory be changed to blend back in the original 512x512 version in the unmasked regions, with an opacity gradient around the edge of the mask.

**Comment by lstein** [comment]
Do you see the non-masked regions changing when both the init image and the mask (if you are using one) are exactly 512x512 (or whatever your specified destination dimensions are)? Otherwise there's going to be some resizing and resampling going on, and information will be lost. In addition, it doesn't help that we are using the image library's default PNG compression level of 9. This causes artifacts that become increasingly evident as you pass the image through many img2img cycles.

In any case, inpainting is a bit of a black box to me, and I'm hoping to work more on it with guidance from AUTOMATIC111's work. He seems to have solved most of the issues. Anybody reading this who wants to help would be most welcome to!

**Comment by smoke2007** [comment]
here's a test with 512x512 , original , masked and generated

labrador is original,

border collie the generated one

as you can see, the woman got destroyed with pixels

![dog-m](https://user-images.githubusercontent.com/17826183/191003657-5922ca89-e085-4bdc-8a10-cf6f7e0cf742.png)

![dog-o](https://user-images.githubusercontent.com/17826183/191003658-4af3f091-e884-459a-a494-1600dd8d9359.png)

![dog-generated](https://user-images.githubusercontent.com/17826183/191003654-73670254-62c3-4302-b6cd-0ced52f60f70.png)

**Comment by CodeExplode** [comment]
SD struggles to encode and decode small faces unfortunately, using the internal description of weights that it understands an image by before rebuilding it at the other.

It's something I've been discovering while doing textual inversion - all my embeddings are (correctly) fitting to messed up faces since that's what the training data turns into when it goes into SD's model (I'm trying to counteract it by writing custom training prompts for those images where they are described as blurry/messed up/corrupted faces so that the embedding is trained to produce those faces with that description, and hopefully can produce more normal faces when that description isn't used in actual prompts).

**Comment by lstein** [comment]
I know it's been a while, but this feature request finally came to the top of my queue. I have just posted PR #1127 which adds a `--png_compression` option that you can use to reduce the compression level or turn it off entirely. This should fix the JPG-like compression artifacts.

**Comment by Kyle0654** [comment]
It sounds like this might not be entirely from writing pngs with compression (unless Pillow does that in-memory). I'm experiencing this on the node branch as well (where everything is kept in-memory). The quality loss from img2img with a mask is pretty substantial.

**Comment by lstein** [comment]
Turns out that this was a problem in the Autoencoder. If you get and load the VAE file vae-ft-mse-840000-ema-pruned.ckpt, it goes a long way towards improving the img2img quality.
