### ISSUE TITLE
Multiple GPU support?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#656]
Is there any plan to have multiple gpu support? And/or the ability to select what gpu to used if many are available?

**Comment by lstein** [comment]
It's on the TODO list (#195 ), but nobody has volunteered to do the work yet. It should be relatively straightforward to select which GPU to use. More work to distribute inference among two or more GPUs.

**Comment by Neosettler** [comment]
Dully noted, thank you lstein. Here's reading of interested on the subject:
https://github.com/NickLucche/stable-diffusion-nvidia-docker

Repo that does it already:
https://stackoverflow.com/questions/54216920/how-to-use-multiple-gpus-in-pytorch

**Comment by Neosettler** [comment]
@lstein Any progress on this front?

**Comment by Mikec78660** [comment]
you can perform this now by setting CUDA_VISIBLE_DEVICES=0 in one terminal and launching invokeai --web and setting CUDA_VISIBLE_DEVICES=1 in another terminal and launching invokeai --web --port 9191. but you have to keep switching back and forth between the two browser tabs. But since I am running a 1050ti as one gpu and a 1030 as the other I have plenty of time to switch :-) I can only scale and delete images with the 1030 as it only has 2gb of ram.

It would be nice to be able to specify 2 GPUs or more, then in the UI have a setting for if you want a reserved GPU. So if you had 2 gpus defined and one reserved when you hit invoke it would only use one but you would be able to scale images or do impainting or perform face reconstruction or even just delete bad images. You could also start another batch or renders with different setting. if you didn't have a GPU set as reserved when you hit invoke it will just use all gpus if you have images set to more than one.
