### ISSUE TITLE
Deduplicate README.md and docs/index.md

### ISSUE THREAD

**Issue by mh-dm** [invoke-ai/InvokeAI#670]
https://github.com/lstein/stable-diffusion/blob/development/docs/index.md
and
https://github.com/lstein/stable-diffusion/blob/development/README.md

Have basically the same content but slightly different implementations. `README.md` has to links to `docs/assets/example` whereas index.md omits the `docs/`. They also have slightly different formatting.

They will inevitably diverge in content and contain outdated information and the duplication creates more maintenance work.

There are probably multiple ways to achieve deduplication. A couple suggestions:
 - moving `README.md` to `docs/` as per "If you put your README file in your repository's hidden .github, root, or `docs` directory, GitHub will recognize and automatically surface your README to repository visitors." Source: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes
- I don't know mkdocs and a bit more complicated but could it pull README.md and process it? (strip `docs/` , fix links)

**Comment by mauwii** [comment]
imho the index.md should not reflect the content of the README.md, since those files have a different purpose (one is the welcome page of the repository, the other one is the welcome page of the documentation). But since I have a lack of creativity sometimes as well as this is not my repository, the best Idea I could come up with yet is [index.md](https://github.com/lstein/stable-diffusion/blob/development/docs/index.md)

But long story short: I think we should come up with a better Idea for the docs welcome page instead of somehow duplicate the repos README.md 😅 (not only because github-flavored markdown and MkDocs have very different features)

**Comment by lstein** [comment]
@mauwii , how does one view the github docs tree using mkdocs, and can this be offered as a link in README.md?

**Comment by mauwii** [comment]
@lstein: Considering you activated gh-pages and published the docs there, then you get a link (like <username>.github.io/<reponame> ). F.e. mine is [https://mauwii.github.io/stable-diffusion](mauwii.github.io/stable-diffusion). This could of course be linked anywhere.

To run it lokaly you need to

```bash
pip install -r requirements-mkdocs.txt
mkdocs serve
```

**Comment by lstein** [comment]
Unfortunately the mkdocs format doesn't appear to interoperate well with plain old markdown. I just had to rip out all the <figure markdown> tags from all the .md files because they were preventing the images from displaying when rendered by GitHub's legacy markdown renderer in the code browser.

I think it might be better to either:

1. Just go ahead and make a nice set of gh-pages for the project, or
2. Start making better use of the WIKI.

There are a number of other annoyances in how mkdocs appear in the code browser, including the empty Title and Description table at the top, and the "material-tune" heading at the top of each page.

**Comment by mauwii** [comment]
I think so, yes

**Comment by mauwii** [comment]
This could be closed @lstein

**Comment by psychedelicious** [comment]
Thanks, closing.
