### ISSUE TITLE
[bug]: Very slow with IPadapter (SDXL)

### ISSUE THREAD

**Issue by KagaroNakaza** [invoke-ai/InvokeAI#6723]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX3050

### GPU VRAM

6GB

### Version number

4.2.7post1

### Browser

Chrome 127.0.6533.89

### What happened

I have an RTX 3050 and the normal generation is very fast, but the moment I add a global IP adapter, 1 generation takes about 15 minutes. Am I doing something wrong? Or is this normal?

### What you expected to happen

that the generation would be fast.

**Comment by psychedelicious** [comment]
It's normal, your GPU doesn't have enough VRAM to hold the both main and IP Adapter models at once.

It's triggering a Windows feature called [shared GPU memory](https://invoke-ai.github.io/InvokeAI/help/FAQ/#shared-gpu-memory-windows), which lets your GPU use some of the system RAM as VRAM. This lets you use bigger models than you'd otherwise be able to use, but is very slow.

You could disable the feature as described in the link, but you'd get an error when attempting to add IP Adapter to SDXL. Unfortunately those are you options with 6GB of VRAM.

**Comment by KagaroNakaza** [comment]
Are there any parameters like med-vram that can be used?

**Comment by psychedelicious** [comment]
No - we suggest 8GB VRAM minimum for SDXL.
