### ISSUE TITLE
[bug]: Database error when attempting to start image generation

### ISSUE THREAD

**Issue by Johmpa** [invoke-ai/InvokeAI#6974]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 3070

### Version number

v5.0.0

### Browser

Chrome 129.0.6668.71

### Python dependencies

{
  "accelerate": "0.30.1",
  "compel": "2.0.2",
  "cuda": "12.1",
  "diffusers": "0.27.2",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.4.0",
  "python": "3.10.9",
  "torch": "2.2.2+cu121",
  "torchvision": "0.17.2+cu121",
  "transformers": "4.41.1",
  "xformers": "0.0.25.post1"
}

### What happened

Attempting to start a standard text2img generation, but invocation generates an unknown error in the UI. The log output seems to indicate a problem with the database, the root cause being `sqlite3.OperationalError: no such column: destination`

Based on this I suspect some migration of the database has failed during an update or some form of corruption. I have attempted a reinstall but this has not worked. I'm reluctant to delete the database and start from scratch as I have a lot of previous generations I want to preserve. 

Full log file:
[invoke_db_error.log](https://github.com/user-attachments/files/17171488/invoke_db_error.log)

### What you expected to happen

A successful invocation of text2img generation. 

### Additional context

I have previously been using a development version and have done repeated updates from the development branch. Perhaps this has done something to the database when updating to v5?

**Comment by Johmpa** [comment]
Rolling back to a previous database backup solved the problem. Relatively little data was lost. Seems like a database migration failed on a previous update.

**Comment by psychedelicious** [comment]
Yes, because you used a development build, your database schema is out of sync. This doesn't mean a migration was unsuccessful.

This kind of issue is the reason we included a message about using a separate db when testing dev builds.

You have a two options:
- Delete the old database and start a fresh one. You'll lose all your data.
- Review the two (minor) changes in the [last migration](https://github.com/invoke-ai/InvokeAI/blob/main/invokeai/app/services/shared/sqlite_migrator/migrations/migration_15.py) and edit your database to match. You can use the sqlite3 CLI to do this pretty easily - open the db file and paste each SQL query from the migration in. Probably will get an error about `origin` saying it already exists, but `destination` should add. Then you should be good to go.
