### ISSUE TITLE
[enhancement]: Swap foreground and background points on Auto Mask

### ISSUE THREAD

**Issue by skunkworxdark** [invoke-ai/InvokeAI#7170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

skunkworxdark

### What should this feature add?

The ability to swap the foreground and background picked points. 

### Alternatives

invert the mask itself

**Comment by psychedelicious** [comment]
I added the ability to invert the selection. I think this better addresses the use-case than switching the points, because it leaves the model's internal "semantics" alone. That is to say, the model is designed to select objects, not the inverse of objects. Closing as completed but happy to discuss further if there's a use-case for inverting the points.
