### ISSUE TITLE
[bug]:  "The repository ... (ubuntu) no longer has a Release file" when running a Docker container on Runopod

### ISSUE THREAD

**Issue by Arhadrianman10** [invoke-ai/InvokeAI#7387]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

other

### GPU vendor

Nvidia (CUDA)

### Version number

5.4.2

### Browser

runpod

### What happened

When running a Docker container on Runopod, I encountered errors indicating that certain Ubuntu repositories no longer have a release file. The full error log is as follows:

2024-11-27T16:36:09.240804704Z E: The repository 'http://archive.ubuntu.com/ubuntu lunar Release' no longer has a Release file.
2024-11-27T16:36:09.240823327Z E: The repository 'http://archive.ubuntu.com/ubuntu lunar-updates Release' no longer has a Release file.
2024-11-27T16:36:09.240828923Z E: The repository 'http://archive.ubuntu.com/ubuntu lunar-backports Release' no longer has a Release file.
2024-11-27T16:36:09.240833523Z E: The repository 'http://security.ubuntu.com/ubuntu lunar-se

### What you expected to happen

I expected the container to run without any issues, as it was working perfectly just three days ago. The repositories were accessible, and all necessary packages installed without errors during that time.

**Comment by stf976** [comment]
I just encountered the same issue rebuilding a docker image based on Ubuntu 23.04.
Following the links in the error message it shows that there is no lunar folder below [http://archive.ubuntu.com/ubuntu/dists/](http://archive.ubuntu.com/ubuntu/dists/)
Presumably it was recently removed after Ubuntu Lunar has reached its End-of-Life in Jan 2024 according to [https://wiki.ubuntu.com/Releases](https://wiki.ubuntu.com/Releases)
Your best bet might be to rebuild or otherwise obtain your container image based on a newer Ubuntu version. If you want a long-term stable release, the latest is 24.04.1 as of now.
