### ISSUE TITLE
Getting an error when trying to use outpainting function

### ISSUE THREAD

**Issue by kriptolix** [invoke-ai/InvokeAI#754]
**Describe your environment**
- GPU: cuda
- VRAM: 6gb
- CPU arch: x86
- OS: Linux
- Python: miniconda
- Branch: development

**Describe the bug**
dream script crash when trying to use outpainting.

**To Reproduce**
1. On dream prompt, use the command `!fix "path-to-an-image" -D top 50`
2. See error

```
badly-formatted metadata
Traceback (most recent call last):
  File "/var/home/k/diffusion/InvokeAI/ldm/dream/args.py", line 748, in metadata_loads
    images = [metadata['sd-metadata']['image']]
KeyError: 'image'

   badly-formatted metadata
Traceback (most recent call last):
  File "/var/home/k/diffusion/InvokeAI/ldm/dream/args.py", line 748, in metadata_loads
    images = [metadata['sd-metadata']['image']]
KeyError: 'image'

Traceback (most recent call last):
  File "/var/home/k/diffusion/InvokeAI/scripts/dream.py", line 453, in <module>
    main()
  File "/var/home/k/diffusion/InvokeAI/scripts/dream.py", line 119, in main
    main_loop(gen, opt, infile)
  File "/var/home/k/diffusion/InvokeAI/scripts/dream.py", line 318, in main_loop
    do_postprocess(gen,opt,image_writer)
  File "/var/home/k/diffusion/InvokeAI/scripts/dream.py", line 374, in do_postprocess
    return gen.apply_postprocessor(
  File "/var/home/k/diffusion/InvokeAI/ldm/generate.py", line 566, in apply_postprocessor
    oldargs      = metadata_from_png(image_path)
  File "/var/home/k/diffusion/InvokeAI/ldm/dream/args.py", line 736, in metadata_from_png
    return opts[0]
IndexError: list index out of range
```

**Expected behavior**
To output a image 50px up outpainting

**Some context**
The error 
```
badly-formatted metadata
Traceback (most recent call last):
  File "/var/home/k/diffusion/InvokeAI/ldm/dream/args.py", line 748, in metadata_loads
    images = [metadata['sd-metadata']['image']]
KeyError: 'image'
```
it also happens when trying to upscale an image with "!fix", but in this case, despite the error, the correct result is generated normally.

**Comment by Ratinod** [comment]
After some testing, I can assume that you are trying to use outpaint on an image that was added manually.
This command: 
`!fix ./outputs/img-samples/imagename.png -D top 50` 
will work only if it can load data (prompt, seed, etc.) from the log file of generated images.
Solution:
use a command like this: 
`your prompt here -I./outputs/img-samples/imagename.png -D top 50`

**Comment by timdesrochers** [comment]
I had the same issue trying to fix images generated from the latest stable release. The metadata format has changed. You can run exiftool on the .png to verify.

Try fixing an image generated with the dev version?

**Comment by lstein** [comment]
This will require some documentation and some code fixes before `development` goes to `main`.

First, outpainting needs a text prompt in order to fill in the missing portions of the image. The best text prompt to use is the exact same one used to generate the image, assuming that the image was generated by the AI. It *may* work on real images if you choose a good prompt, but this hasn't been tested.

To get the original prompt on AI-generated images the script reads the metadata from the previously-generated image. However, the metadata format has been changing and is only recently stabilized. As a result, there are a mixture of images with no metadata, legacy metadata, and new metadata.

I am going to fix the code so that it recognizes older metadata formats and gives a more user-friendly error message when the metadata can't be found or reconstructed. Meanwhile, what you can do is to use @Ratinod 's method to manually apply your own prompt to the image.

**Comment by kriptolix** [comment]
Ok, thanks guys.
