### ISSUE TITLE
Upscaling doesnt cooperate with new webUI

### ISSUE THREAD

**Issue by ioma8** [invoke-ai/InvokeAI#796]
**Describe your environment**
- GPU: cpu
- VRAM: [if known]
- CPU arch: arm
- OS: macOS
- Python: Anaconda
- Branch: development
- Commit: 636c356aafdeceab646648bcb25ba38c16a49e32

**Describe the bug**
Using the new webUI. When I select any image from right gallery and click on upscale (have settings for 4x), the progressbar animates for a while, then it says "Disconnected." But the upscaling continues (as shown in terminal). When upscaling is finished, webUI shows "Connected" again, but gallery on the right side doesnt update. I have to refresh the browser, for it to show the newly upscaled image (upscale finishes correctly just webUI didnt learn that) 

<img width="357" alt="image" src="https://user-images.githubusercontent.com/6624752/192132524-0f375e87-32fa-4038-95bc-4c7bd0ff6b79.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/6624752/192132536-b1a15a25-3beb-48e9-899c-288e0bc01d01.png">

**Comment by ioma8** [comment]
probably relates to https://github.com/invoke-ai/InvokeAI/pull/786

**Comment by psychedelicious** [comment]
Hi, it is because upscaling is a thread-blocking task and the server is unable to maintain its socket connection to the client. I have the same issue. #799 increases the timeout values and should help. I will add an listener to reconnect events that updates the gallery, so if something does time out, it automatically updates when the server is free again.

I will leave this issue open as a reminder to add the refresh on reconnect.

**Comment by ioma8** [comment]
@psychedelicious Thank you! Just a question as I am not at all familiar with how it works in python. Isnt it possible to make the webserver (sockets) run in separate thread?

**Comment by psychedelicious** [comment]
@ioma8 No worries. I'm sure there is a way, but I only know enough to be dangerous and alas, in this case, not quite enough to be useful. I only wrote my server script because the old UI's server wasn't quite enough to let me build the UI I wanted to build.

We have a new server and API on the way which, I believe, are properly threaded. Somebody who knows what they are doing are making them :)

**Comment by psychedelicious** [comment]
#807 adds gallery refresh on reconnect
