### ISSUE TITLE
Inpainting doesn't allow for transparent borders

### ISSUE THREAD

**Issue by vadi2** [invoke-ai/InvokeAI#803]
I have an image with transparency around the borders - and unfortunately, this transparency is being treated as a mask, which is not what I'd like.

Original image:

![original](https://user-images.githubusercontent.com/110988/192162929-1a848ff6-34a6-4531-a509-3882b3965910.png)

Mask - where I'd only like the contents of the arch to be painted:

![original-mask](https://user-images.githubusercontent.com/110988/192162965-7e418676-32ca-4321-b9e8-a5f30ef6c744.png)

Sample resulting image with contents outside the mask being painted:

![image](https://user-images.githubusercontent.com/110988/192162989-a7b8bc8f-6a8f-4a54-866f-190b383922c5.png)

**Comment by hipsterusername** [comment]
I think the challenge here is with expectations.

Inpainting is currently controlled by passing transparency into Invoke, and requesting the system paint everything that's transparent. The fact that it's painting everywhere that is transparent is **expected behavior.**

For achieving the desired outcome above, I'd make the area outside the arch black instead of transparent, and remove the black after the fact.

**Comment by lstein** [comment]
@hipsterusername  is correct. If you want finer control, then explicitly pask a mask image. The code then *ought* to ignore whatever transparency is present in the image itself and only use the mask data. If you find that it isn't doing this, then please report it as a bug.
