### ISSUE TITLE
Web server backend crashes if a file in local storage is missing

### ISSUE THREAD

**Issue by lstein** [invoke-ai/InvokeAI#817]
**Describe your environment**
- GPU: CUDA
- VRAM: 24 GB
- CPU x86
- OS: Linux
- Python: Anaconda, python 3.9
- Branch: development
- Commit: 14616f41786b2282e3686d86b2c79f9ddc95f479

**Describe the bug**
I recently deleted all the contents of my output directory. Now the web server backend gives a FileNotFound error whenever I try to perform a render. I had to reset the WebUI in order to get back to a usable state.

**To Reproduce**
1. Generate a bunch of images
2. Turn off the backend server (may not be necessary)
3. Delete the images
5. Restart the server
6. Try to generate a new prompt
7. Generation fails with a FileNotFound error on one of the previously generated and now deleted images.

**Comment by psychedelicious** [comment]
I can recreate this error if I set an image as the initial or mask image, delete that file and then attempt to run an img2img. 

The bigger issue this points to is the lack of error handling in the server I wrote. I already have an error messaging system set up - errors are sent to the UI and logged in the console. 

But there is only a single `try-except` block which covers a single `prompt2image` call - I added this ages ago and haven't though about it since:

https://github.com/invoke-ai/InvokeAI/blob/development/backend/server.py#L791-L806

Proposed UI improvements:
- Make a small "toast" style 5-second popup in the UI whenever an error is logged
- Turn the log viewer expand button red when an error is logged as another indication in case you miss the toast - when you expand the log viewer it goes back to its normal color

Proposed error-handling improvements:
- Wrap basically the whole server script in a try-except - so take this current limited error handling code:  and expand it to cover the whole server. This way any errors will be caught and sent to UI. Is this a bad pattern? Please advise  @blessedcoolant @tildebyte
