### ISSUE TITLE
Add CodeFormers to new WebUI next to GFPGAN

### ISSUE THREAD

**Issue by ioma8** [invoke-ai/InvokeAI#832]
**Describe the solution you'd like**
As there is option to use GFPGAN for face restoration, I would like to be able to use CodeFormers from the new WebUI as it works better for some cases / has better options

**Comment by hipsterusername** [comment]
Unconfirmed, but I think Codeformer is being used as part of the general "face correction" process/flow. I don't think you have to specify between the two. Someone else can correct me if I'm wrong - I've just noticed the face correction quality has improved since Codeformer model was implemented, without any specification in the UI.

**Comment by lstein** [comment]
@psychedelicious It looks like codeformer support is incomplete in the WebGUI. It isn't clear to me that this is a high priority, as 
GFPGAN was recently updated and is now producing better results than codeformer to my eye.

**Comment by hipsterusername** [comment]
My daily reminder correlation =/= causation 🙈

**Comment by psychedelicious** [comment]
This should be a relatively straightforward thing to add but will need to wait until I've sorted out a few small bugs and then done some refactoring to better accommodate additional models (? technologies? methods?) of face correction and upscaling in both server and client.

**Comment by michaelezra** [comment]
it would be useful to have the UI option to select a desired method
