### ISSUE TITLE
Support for Textual Inversion Models?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#837]
Greetings, 

are the .pt format supported? If not, is there plans to do so?

[](https://cyberes.github.io/stable-diffusion-textual-inversion-models/)

Thank you,

**Comment by tildebyte** [comment]
#814 number 4 shows how to use a custom embedding. There might also be something in the docs (which I should probably get around to reading at some point 🙄)

**Comment by happylittlecloud** [comment]
I can confirm that calling dream.py with the Usada Pekora.pt file from [the showcase](https://github.com/AUTOMATIC1111/stable-diffusion-webui-feature-showcase) will work correctly for me on Windows. However, doing the training myself locally, I had no luck so far with the resulting .pt files. Although dream.py seems to start correctly, my style file seems to wreck it entirely so that it does not generate images at all. 
I can use the .bin files from the Diffusers concept library or trained myself via their colab using the keyword (not the placeholder, though).

**Comment by psychedelicious** [comment]
The .pt format is supported; closing. @happylittlecloud - if you have a problem with .pt files or .bin files, please create an issue for that specific issue.
