### ISSUE TITLE
GFPGAN and Real-ESRGAN with 4X upscale?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#905]
Greetings,

Using GFPGAN and Real-ESRGAN with upscale 2x works beautifully (image looks the same as face restore only but with better resolution). When upscaling to 4x, the resulting image has been altered compared to face restore only and the 2x but not in a good way. 

Any idea what could be at fault here and/or how to prevent this from altering the face restore?

thank you,

**Comment by psychedelicious** [comment]
Please give us a bit more detail by filling out the issue form as best you can - we really need this info to help you, preferably including the steps you took to run gfpgan/esrgan and output images to show us what is going on:

**Describe your environment**
- GPU: [cuda/amd/mps/cpu]
- VRAM: [if known]
- CPU arch: [x86/arm]
- OS: [Linux/Windows/macOS]
- Python: [Anaconda/miniconda/miniforge/pyenv/other (explain)]
- Branch: [if `git status` says anything other than "On branch main" paste it here]
- Commit: [run `git show` and paste the line that starts with "Merge" here]

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by psychedelicious** [comment]
Hi @Neosettler , is this still an issue?

**Comment by psychedelicious** [comment]
No response, closing
