### ISSUE TITLE
Deleted Image displayed when generating new image (WebUI)

### ISSUE THREAD

**Issue by hipsterusername** [invoke-ai/InvokeAI#940]
**Describe your environment**
- GPU: [cuda]
- VRAM: 12
- CPU arch: x86
- OS: Windows
- Python: Anaconda
- Branch: dev

**Describe the bug**
Deleting an image, and then generating a new image with a different W/H parameter displays the previous image. (Note: Actual file generated in outdir is correct)

**To Reproduce**
1. Generate an image using the prompt `close-up of a Japanese teen singing sensation looking directly into camera` at W 512 and H 576 and the seed `634966792`
2. Delete the generation
3. Change H to 512
4. Regenerate the image.
5. See old image in the preview window.

**Expected behavior**
Newly generated image is correctly displayed.

**Comment by Any-Winter-4079** [comment]
How do you delete the generation? From the web?
<img width="60" alt="Screenshot 2022-10-05 at 22 51 56" src="https://user-images.githubusercontent.com/50542132/194161148-79d8a1f3-d980-4181-954c-c4836ea81bb0.png">

**Comment by hipsterusername** [comment]
Using the Trashcan button on the gallery image

**Comment by psychedelicious** [comment]
Ya this is happening bc the file name prefix generator is just incrementing from whatever the last image was called, plus uses the seed. So if you use the same seed and delete the image, you'll get the same filename. 

I think we should use a short uuid instead of an incrementing number, or perhaps in addition to it. 

More generally we should think about how we want to name images.

**Comment by psychedelicious** [comment]
Fixed in #940
