### ISSUE TITLE
Request: can WebUI image gallery drawer slide out next to the image panel instead of overlaying?

### ISSUE THREAD

**Issue by griffwill** [invoke-ai/InvokeAI#999]
saw that the image gallery feature is now in the WebUI and the image drawer can be hidden. this is nice, but when it is open on the txt2img pane, it will overlay the main image panel (thus occluding the main preview depending on window size) vs the previous layout of being next to the main preview. The later layout feels a lot more streamlined when working in the txt2img pane to review multiple generations. 

I can see why the current behavior may be preferred as well, so potentially this should be a user defined behavior?

**Comment by hipsterusername** [comment]
@blessedcoolant - Think this makes sense, especially in the context of a "working" gallery.

**Comment by blessedcoolant** [comment]
The reason to pull it out completely was that the canvas gets as much breathing room as possible. If I add it back in there and let it slide, then it goes back to what it was before.

Not to mention, having it overlayed lets you expand it to full screen which allows us to add gallery management features in a neat UI later.

I understand that at the moment it occludes the canvas when it is open but I made this trade off for the time being in the expectation that when the gallery is being interacted with at the moment, there isn't much to do on the canvas. The only shared feature is going through the images and you can just use the arrow keys to do that right now too.

I know this is not a perfect solution yet, but I don't think we should go back to putting it in the same pane as the canvas and slide in and out. Because that brings back the spacing restrictions.

I am exploring solutions to improve this experience but that is in the scope of a future patch.

**Comment by hipsterusername** [comment]
@blessedcoolant - I don't think anyone is arguing that a collapsed option shouldnt exist, but an overlayed drawer offers no immediate benefit over an expanded drawer that remains open. It has less functional applications for those people who are using it as a 'working drawer' (I made this comment last night as it was being worked on)

4 use cases -- 
Closed > Don't care about it
Expanded > Constantly moving between canvas/gallery (common pattern for high speed iterations)
Expand/close > Open to quickly review/grab something, and then close it again
Full Screen > More extensive gallery management.

Overlay impedes the "Expanded" use case, while an expandable drawer serves all four

**Comment by griffwill** [comment]
@blessedcoolant, I agree that other options should be prioritized, but as @hipsterusername mentioned, the previous set up allows for a working gallery view that offers the ability to have similar workflow to existing editing/gallery apps. I am often keying back and forth between iterations to see what areas are being kept/changing with different settings, so having both the image drawer and main preview fully visible is helpful, particularly when I am working in a smaller window/screen. Like I mentioned, this could be a user defined setting if there’s a desire for both layouts.

**Comment by netsvetaev** [comment]
also, we can make it smaller and zoom on hover to save some space — this solves smaller screens problems too. 
![image](https://user-images.githubusercontent.com/83028930/194722392-e5349115-492e-46ee-8255-6ea1c5c61d61.png)

**Comment by blessedcoolant** [comment]
@griffwill Well that was a lot of discussion here and on discord but I made some changes. Check PR #1000

**Comment by blessedcoolant** [comment]
> also, we can make it smaller and zoom on hover to save some space — this solves smaller screens problems too. ![image](https://user-images.githubusercontent.com/83028930/194722392-e5349115-492e-46ee-8255-6ea1c5c61d61.png)

Done

**Comment by 19wolf** [comment]
Not sure if this belongs here or in another issue, (I think I saw it discussed on discord) but on release-candidate-2 at least, when I expand the gallery and then shrink it, the columns don't shrink, they just push off the side of the screen.

**Comment by 19wolf** [comment]
I also definitely do not prefer the image height being tied to the screen height. If it's smaller, let it be smaller.

**Comment by lstein** [comment]
I think the latest commit fixes this behavior.
